### ISSUE TITLE
File transfer via jit.si

### ISSUE THREAD

**Issue by rjb25** [jitsi/jitsi#132]
When I drag and drop messages in to the chat I get the following error.
The above message could not be delivered, failed to deliver.
My operating system is Ubuntu 14.04.2 LTS
My jitsi version is Jitsi 2.8.5426
this is the command line error
18:50:10.521 SEVERE: [140] impl.protocol.jabber.OperationSetFileTransferJabberImpl.run().654 An error occured while transfering file: The remote user did not respond or the connection timed out.
Also here is the link to the stack exchange question
http://security.stackexchange.com/questions/91222/how-can-i-transfer-files-securely-with-jitsi-on-the-jit-si-network
It finally worked out of the blue, must have been a connection error.
there was no command line response when it worked.

**Comment by v6** [comment]
// , Can you add some code to that, please?

**Comment by v6** [comment]
// , Tried it out myself. Got this: 

![selection_003](https://cloud.githubusercontent.com/assets/5750764/8071603/a6572fa4-0ec0-11e5-98dc-9528ddb615d3.png)

**Comment by v6** [comment]
// , Sometimes it work, 'n sometimes it dn't.

**Comment by v6** [comment]
// , Here's the code related to the WhenIsGood(5)-1.ics file: 

    15:58:16.681 SEVERE: [232] impl.protocol.jabber.OperationSetFileTransferJabberImpl.run().660 An exception occured while transfering file:
    Error in execution:
      -- caused by: java.util.concurrent.ExecutionException: No response from file transfer initiator:
        at org.jivesoftware.smackx.filetransfer.IncomingFileTransfer.negotiateStream(IncomingFileTransfer.java:199)
        at org.jivesoftware.smackx.filetransfer.IncomingFileTransfer.access$100(IncomingFileTransfer.java:47)
        at org.jivesoftware.smackx.filetransfer.IncomingFileTransfer$1.run(IncomingFileTransfer.java:124)
        at java.lang.Thread.run(Thread.java:745)
    Nested Exception:
    java.util.concurrent.ExecutionException: No response from file transfer initiator:
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:202)
        at org.jivesoftware.smackx.filetransfer.IncomingFileTransfer.negotiateStream(IncomingFileTransfer.java:193)
        at org.jivesoftware.smackx.filetransfer.IncomingFileTransfer.access$100(IncomingFileTransfer.java:47)
        at org.jivesoftware.smackx.filetransfer.IncomingFileTransfer$1.run(IncomingFileTransfer.java:124)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: No response from file transfer initiator:
        at org.jivesoftware.smackx.filetransfer.StreamNegotiator.initiateIncomingStream(StreamNegotiator.java:97)
        at org.jivesoftware.smackx.filetransfer.IBBTransferNegotiator.createIncomingStream(IBBTransferNegotiator.java:80)
        at org.jivesoftware.smackx.filetransfer.IncomingFileTransfer$2.call(IncomingFileTransfer.java:186)
        at org.jivesoftware.smackx.filetransfer.IncomingFileTransfer$2.call(IncomingFileTransfer.java:183)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at org.jivesoftware.smackx.filetransfer.IncomingFileTransfer.negotiateStream(IncomingFileTransfer.java:190)
        ... 3 more


The successful transfer produced no errors.

**Comment by v6** [comment]
// , Why was this closed?

**Comment by v6** [comment]
// , Pretty serious bug, if someone asked me.

**Comment by imp1sh** [comment]
I also have this issue, when I try to send someone an amazon link on version 2.10.5550 on a Mac to a Windows host running the exact same version.

**Comment by v6** [comment]
// , I think most people find a way to deal with it by generic troubleshooting, but it's still a pretty ambiguous error.

**Comment by v6** [comment]
// , @ibauersachs, would you consider re-opening this?
