### ISSUE TITLE
Jitsi on Linux gives on each startup a NullPointerException in PluginManagerActivator

### ISSUE THREAD

**Issue by ArthurBorsboom** [jitsi/jitsi#165]
Using Jitsi-nightly:

java.lang.NullPointerException
	at net.java.sip.communicator.plugin.pluginmanager.PluginManagerActivator.start(PluginManagerActivator.java:99)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2220)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2138)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1365)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ibauersachs** [comment]
Please send your complete [logs](https://jitsi.org/logs) (don't post them as a message, create a Gist or send it to the mailing list, where prefer a first discussion anyway) and describe exactly what you did, which distribution you're running, which desktop environment and which Jitsi build.

**Comment by ArthurBorsboom** [comment]
Linux: Arch x64, kernel 4.2.3
DE: Lxqt 0.9

Way to reproduce: Start Jitsi
Where to find error message: in .xsession-errors (or in console if started from console)
Log file: https://download.aramgroup.com/jitsi0.log.0

If more information is needed, please let me know.

**Comment by ibauersachs** [comment]
The logfile you sent doesn't contain the error. As a wild guess, I'd assume that Arch uses shared libraries (which we normally bundle) and these don't contain the necessary OSGi manifest. A prime example for that has been [log4j on Ubuntu](https://bugs.launchpad.net/ubuntu/+source/axis/+bug/894302).

I'm closing this issue because Jitsi 2.9.20151014, the version mentioned in your log, is a custom build and we cannot really support that. But feel free to leave further logs and comments.
