### ISSUE TITLE
Memory is Exhausted in Windows when using SIP account

### ISSUE THREAD

**Issue by vccs** [jitsi/jitsi#177]
I wanted to open this as a bug in case it's not being addressed already. There is a prior mailing thread but min is located here: http://lists.jitsi.org/pipermail/users/2015-October/010364.html

After 20 mins or so windows will close all applications in an attempt to free up RAM which is exhausted by Jitsi. I have tried suggestions such as using 2.8 stable, and 2.9 nightly,  both while disabling MWI. If explained how I can certainly get some further logs.

Thank you.

**Comment by ibauersachs** [comment]
We need your [logs](https://jitsi.org/logs). And it seems like a rather unusual situation, so please don't expect any quick solutions.

**Comment by vccs** [comment]
Thank you for the feedback. Here is one users log cap from April: http://lists.jitsi.org/pipermail/users/2015-April/009323.html

Also I only managed to snag 1 error log but not sure what to make of it: 
-------------------------
2015-11-02 00:13:05.677 SEVERE: [166] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x8889000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2227)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2459)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2567)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:43)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2689)
2015-11-02 00:13:05.681 INFO: [18] impl.neomedia.NeomediaActivator.start().542 Audio Notifier Service ...[REGISTERED]
2015-11-02 00:13:05.694 SEVERE: [166] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x8889000a
-----------------------

After my efforts to reproduce it, I can no longer. The error happened on several versions using the executable windows release. Once I installed the MSI the issue didn't re-occur. I then uninstalled the msi and reinstalled the exe version and it hasn't happened again. As I'm not a programmer I can only attribute this to something in the MSI, perhaps a dependency that was installed stabilized the issue.

Thank you.

**Comment by ibauersachs** [comment]
The exe is just a wrapper around the msi. Closing this because of no repro and incomplete logs.

**Comment by vccs** [comment]
This error still exists. Not sure about the conditions though. Same error in log:

2015-11-07 18:39:05.130 SEVERE: [905] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x8889000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2227)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2459)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2567)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:43)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2689)
2015-11-07 18:39:05.210 SEVERE: [905] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x8889000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2227)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2459)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2567)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:43)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2689)
2015-11-07 18:39:05.241 SEVERE: [905] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x8889000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2227)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2459)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2567)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:43)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2689)

How can I help debug this further?

**Comment by ibauersachs** [comment]
As I said, we need your logs and not just some snippets.

**Comment by vccs** [comment]
That error message is repeated dozens of times in the same second followed by:

2015-11-07 18:39:05.341 INFO: [918] org.jitsi.impl.neomedia.MediaStreamImpl.info() 
Receive stream stats: discarded RTP packets: 1495
Receive stream stats: decoded with FEC: 0
2015-11-07 18:39:05.343 INFO: [918] net.sf.fmj.media.Log.info() Stopping RTPSourceStream.
2015-11-07 18:39:05.353 INFO: [918] org.jitsi.impl.neomedia.MediaStreamImpl.info() rtpstat:call stats for outgoing audio stream SSRC: 1166633098
rtpstat:bytes sent: 0
rtpstat:RTP sent: 0
rtpstat:remote reported min interarrival jitter: -0.125ms
rtpstat:remote reported max interarrival jitter: 0.0ms
rtpstat:local collisions: 0
rtpstat:remote collisions: 0
rtpstat:RTCP sent: 0
rtpstat:transmit failed: 0
2015-11-07 18:39:05.353 INFO: [918] org.jitsi.impl.neomedia.MediaStreamImpl.info() rtpstat:call stats for incoming rtpmap:0 PCMU/8000 stream SSRC: 2790835510
rtpstat:packets received: 1524
rtpstat:bytes received: 261288
rtpstat:packets lost: 0
rtpstat:min interarrival jitter: -1
rtpstat:max interarrival jitter: 0
rtpstat:RTCPs received: 0
rtpstat:bad RTCP packets: 0
rtpstat:bad RTP packets: 10
rtpstat:local collisions: 0
rtpstat:malformed BYEs: 0
rtpstat:malformed RRs: 0
rtpstat:malformed SDESs: 0
rtpstat:malformed SRs: 0
rtpstat:packets looped: 0
rtpstat:remote collisions: 0
rtpstat:SRs received: 0
rtpstat:transmit failed: 0
rtpstat:unknown types: 0
2015-11-07 18:39:05.355 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Total packets added: 1514
2015-11-07 18:39:05.356 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Times reset() called: 1
2015-11-07 18:39:05.357 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Times grow() called: 11
2015-11-07 18:39:05.357 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Packets dropped because full: 1486
2015-11-07 18:39:05.357 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Packets dropped while shrinking: 9
2015-11-07 18:39:05.357 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Packets dropped because they were late: 0
2015-11-07 18:39:05.357 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Packets dropped because they were late by more than MAX_SIZE: 0
2015-11-07 18:39:05.357 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Packets dropped in reset(): 0
2015-11-07 18:39:05.357 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Max size reached: 16
2015-11-07 18:39:05.358 INFO: [918] net.sf.fmj.media.Log.info() net.sf.fmj.media.rtp.RTPSourceStream Adaptive jitter buffer mode was enabled
2015-11-07 18:39:05.358 INFO: [918] net.sf.fmj.media.Log.info() Stopping RTPSourceStream.
2015-11-07 18:39:05.415 SEVERE: [905] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x8889000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2227)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2459)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2567)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:43)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2689)
2015-11-07 18:39:05.428 INFO: [918] net.sf.fmj.media.Log.info() Stopping RTPSourceStream.
2015-11-07 18:39:05.442 INFO: [915] net.sf.fmj.media.Log.info() Stopping RTPSourceStream.
2015-11-07 18:39:05.443 INFO: [918] net.sf.fmj.media.Log.info() Stopping RTPSourceStream.

Im not sure that is the cause so I will spend the next couple of days replicating the issue.

**Comment by vccs** [comment]
23:09:55.515 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.520 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.524 SEVERE: [32] org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.error() IAudioClient_GetCurrentPadding
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x88890004
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPI.IAudioClient_GetCurrentPadding(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.runInEventHandleCmd(WASAPIRenderer.java:1508)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.access$000(WASAPIRenderer.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer$2.run(WASAPIRenderer.java:1763)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23:09:55.525 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.531 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.534 SEVERE: [32] org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.error() IAudioClient_GetCurrentPadding
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x88890004
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPI.IAudioClient_GetCurrentPadding(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.runInEventHandleCmd(WASAPIRenderer.java:1508)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.access$000(WASAPIRenderer.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer$2.run(WASAPIRenderer.java:1763)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23:09:55.536 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.541 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.545 SEVERE: [32] org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.error() IAudioClient_GetCurrentPadding
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x88890004
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPI.IAudioClient_GetCurrentPadding(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.runInEventHandleCmd(WASAPIRenderer.java:1508)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.access$000(WASAPIRenderer.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer$2.run(WASAPIRenderer.java:1763)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23:09:55.546 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.552 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.555 SEVERE: [32] org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.error() IAudioClient_GetCurrentPadding
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x88890004
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPI.IAudioClient_GetCurrentPadding(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.runInEventHandleCmd(WASAPIRenderer.java:1508)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.access$000(WASAPIRenderer.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer$2.run(WASAPIRenderer.java:1763)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
23:09:55.557 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.562 SEVERE: [33] org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.error() IMediaObject_ProcessOutput
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x87cc000a
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.VoiceCaptureDSP.IMediaObject_ProcessOutput(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.processOutput(WASAPIStream.java:2218)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2450)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.runInProcessThread(WASAPIStream.java:2558)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream.access$400(WASAPIStream.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPIStream$4.run(WASAPIStream.java:2680)
23:09:55.565 SEVERE: [32] org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.error() IAudioClient_GetCurrentPadding
org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.HResultException: 0x88890004
	at org.jitsi.impl.neomedia.jmfext.media.protocol.wasapi.WASAPI.IAudioClient_GetCurrentPadding(Native Method)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.runInEventHandleCmd(WASAPIRenderer.java:1508)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer.access$000(WASAPIRenderer.java:34)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.WASAPIRenderer$2.run(WASAPIRenderer.java:1763)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MauiAggie** [comment]
I have seen the same. I think this is related to the same issue I am having with the WASAPI processThread being spawned and never cleaning itself up. See http://lists.jitsi.org/pipermail/dev/2015-November/025734.html for my experiences. The threads either in the Jitsi WASAPI code or the lower-level JMF code do not clean up after themselves completely. After as few as 40 calls, in my case, the thread count is near 400 threads and continues to grow with each new call. I see the same processThread create a single thread on a new pool each time. After about 60 calls, the CPU usage is near 100% from all the (still) active threads, and the machine is very sluggish.

I did notice that, by switching from WASAPI to PortAudio, I get different (and not as many) errors and corresponding threads. You might try that in the audio settings. I thought PortAudio just "wrapped" WASAPI on Windows, but apparently, it is more complex than just that.

**Comment by vccs** [comment]
Thanks for the input and suggestion Maui. That is quite beyond my scope of understanding but I can switch the audio and try that out.. Due to that it happens after several hours of the app being open, Im trying to narrow in on a conflicting process perhaps. I have left the app over night with my browser and email open and the error didnt happen, how ever maybe coincidense it happens eventually when I run another softphone. (zoiper in this case) .. Im wondering if when another application has locked the audio and jitsi cant take control of it, it eventually exhausts itself. I say this because I noticed that Jitsi can not use audio when the zoiper app is open. The devices are listed and enabled but no audio comes in or out on a SIP call, how ever the sounds in the test wizard come out fine..
