### ISSUE TITLE
Cannot start Jitsi in Ubuntu 15.10 

### ISSUE THREAD

**Issue by petre2dor** [jitsi/jitsi#179]
I installed `jitsi_2.5-latest_amd64.deb` and this what I get when I get when I run `jitsi`:
```
jitsi                                  
java.awt.HeadlessException
	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:117)
	at net.java.sip.communicator.impl.splashscreen.SplashScreenActivator.start(SplashScreenActivator.java:59)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
	at java.lang.Thread.run(Thread.java:745)
12:42:54.303 SEVERE: [13] impl.configuration.ConfigurationActivator.error() Error creating c lib instance for fixing file permissions
java.lang.UnsatisfiedLinkError: Can't obtain static method dispose from class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:116)
	at net.java.sip.communicator.impl.configuration.ConfigurationActivator.fixPermissions(ConfigurationActivator.java:112)
	at net.java.sip.communicator.impl.configuration.ConfigurationActivator.start(ConfigurationActivator.java:74)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
	at java.lang.Thread.run(Thread.java:745)
ALSA lib pcm_dsnoop.c:614:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2267:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dmix.c:963:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1024:(snd_pcm_dmix_open) unable to open slave
12:42:54.893 SEVERE: [13] org.jitsi.impl.neomedia.device.DeviceConfiguration.error() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer with JMF.
java.lang.UnsatisfiedLinkError: /usr/share/jitsi/lib/native/libjnawtrenderer.so: /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/../lib/amd64/libjawt.so: symbol awt_Unlock, version SUNWprivate_1.1 not defined in file libmawt.so with link time reference
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer.<clinit>(JAWTRenderer.java:90)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1034)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:355)
	at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:141)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:133)
	at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:86)
	at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:163)
	at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:115)
	at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:380)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
	at java.lang.Thread.run(Thread.java:745)
12:42:55.132 SEVERE: [13] impl.osdependent.SystemTray.getDefaultSystemTray().64 Failed to initialize the desktop.tray implementation.
12:42:55.133 SEVERE: [36] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[AWT-EventQueue-0,6,main] and message was: null
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
	at java.awt.Window.<init>(Window.java:535)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:174)
	at net.java.sip.communicator.plugin.desktoputil.SIPCommFrame.<init>(SIPCommFrame.java:84)
	at net.java.sip.communicator.impl.gui.main.MainFrame.<init>(MainFrame.java:180)
	at net.java.sip.communicator.impl.gui.UIServiceImpl.loadApplicationGui(UIServiceImpl.java:148)
	at net.java.sip.communicator.impl.gui.GuiActivator$1.run(GuiActivator.java:168)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
12:42:55.134 SEVERE: [13] impl.osdependent.SystemTray.getDefaultDesktop().62 Failed to initialize the java.awt.SystemTray implementation.
java.lang.UnsupportedOperationException: java.lang.reflect.InvocationTargetException
	at net.java.sip.communicator.impl.osdependent.Desktop$AWTDesktopPeer.<init>(Desktop.java:180)
	at net.java.sip.communicator.impl.osdependent.Desktop.getDefaultDesktop(Desktop.java:58)
	at net.java.sip.communicator.impl.osdependent.DesktopServiceImpl.<init>(DesktopServiceImpl.java:30)
	at net.java.sip.communicator.impl.osdependent.OsDependentActivator.start(OsDependentActivator.java:87)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.java.sip.communicator.impl.osdependent.Desktop$AWTDesktopPeer.<init>(Desktop.java:172)
	... 9 more
Caused by: java.awt.HeadlessException
	at java.awt.Desktop.getDesktop(Desktop.java:142)
	... 14 more
12:42:55.135 SEVERE: [13] impl.osdependent.SystemTray.getDefaultDesktop().70 Failed to initialize the desktop.tray implementation.
java.lang.UnsupportedOperationException: Failed to initialize the desktop.tray implementation.
	at net.java.sip.communicator.impl.osdependent.Desktop.getDefaultDesktop(Desktop.java:72)
	at net.java.sip.communicator.impl.osdependent.DesktopServiceImpl.<init>(DesktopServiceImpl.java:30)
	at net.java.sip.communicator.impl.osdependent.OsDependentActivator.start(OsDependentActivator.java:87)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
	at java.lang.Thread.run(Thread.java:745)
java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libjawt.so: /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libjawt.so: symbol awt_Unlock, version SUNWprivate_1.1 not defined in file libmawt.so with link time reference
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1872)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at org.jdesktop.jdic.misc.impl.LinuxAlerter.<init>(LinuxAlerter.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at org.jdesktop.jdic.misc.Alerter.loadLinux(Unknown Source)
	at org.jdesktop.jdic.misc.Alerter.newInstance(Unknown Source)
	at net.java.sip.communicator.plugin.chatalerter.ChatAlerterActivator.start(ChatAlerterActivator.java:88)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
	at java.lang.Thread.run(Thread.java:745)
^Cjava.lang.IllegalArgumentException: Listener is null
	at org.apache.felix.framework.util.EventDispatcher.removeListener(EventDispatcher.java:298)
	at org.apache.felix.framework.Felix.removeServiceListener(Felix.java:2875)
	at org.apache.felix.framework.BundleContextImpl.removeServiceListener(BundleContextImpl.java:258)
	at net.java.sip.communicator.impl.argdelegation.ArgDelegationActivator.stop(ArgDelegationActivator.java:125)
	at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:651)
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2278)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1215)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Listener is null
	at org.apache.felix.framework.util.EventDispatcher.removeListener(EventDispatcher.java:298)
	at org.apache.felix.framework.Felix.removeServiceListener(Felix.java:2875)
	at org.apache.felix.framework.BundleContextImpl.removeServiceListener(BundleContextImpl.java:258)
	at net.java.sip.communicator.impl.argdelegation.ArgDelegationActivator.stop(ArgDelegationActivator.java:125)
	at org.apache.felix.framework.util.SecureAction.stopActivator(SecureAction.java:651)
	at org.apache.felix.framework.Felix.stopBundle(Felix.java:2278)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1215)
	at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by ibauersachs** [comment]
Please try with either 2.8 stable or the 2.9.x nightlies. Whatever package is still in Debian/Ubuntu (I think it was removed there) doesn't work due to missing external dependencies.

**Comment by petre2dor** [comment]
same thing :(

**Comment by petre2dor** [comment]
2.9 something had better error messages and I got it running :)
Thanks @ibauersachs
