### ISSUE TITLE
Failed to register protocol provider

### ISSUE THREAD

**Issue by rodrigocorsi2** [jitsi/jitsi#187]
I can't to login, when I try I receive an error:
*"An error occurred while logging in with account:..."*

__log file: jitsi0.log.0__
```
2015-11-16 16:55:04.136 INFO: [404] impl.certificate.CertificateServiceImpl.getTrustManager().682 Using Windows-ROOT. Aliases sucessfully renamed on 72 root certificates.
2015-11-16 16:55:04.136 SEVERE: [404] util.account.LoginManager.run().442 Failed to register protocol provider. 
java.lang.ArrayIndexOutOfBoundsException: 0
	at sun.security.mscapi.KeyStore.engineGetCertificate(KeyStore.java:320)
	at sun.security.mscapi.KeyStore$ROOT.engineGetCertificate(KeyStore.java:66)
	at java.security.KeyStore.getCertificate(KeyStore.java:1081)
	at sun.security.validator.KeyStores.getTrustedCerts(KeyStores.java:102)
	at sun.security.ssl.X509TrustManagerImpl.<init>(X509TrustManagerImpl.java:78)
	at sun.security.ssl.TrustManagerFactoryImpl$PKIXFactory.getInstance(TrustManagerFactoryImpl.java:261)
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:78)
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
	at net.java.sip.communicator.impl.certificate.CertificateServiceImpl.getTrustManager(CertificateServiceImpl.java:692)
	at net.java.sip.communicator.impl.certificate.CertificateServiceImpl.getTrustManager(CertificateServiceImpl.java:604)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.getTrustManager(ProtocolProviderServiceJabberImpl.java:1350)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1157)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:944)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:755)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:468)
	at net.java.sip.communicator.util.account.LoginManager$RegisterProvider.run(LoginManager.java:434)
```

__I am using Windows 10 Pro and jitsi-2.9.5485-x64__

Complete Log
```
2015-11-16 17:12:42.602 INFO: [20] plugin.windowscleanshutdown.CleanShutdownActivator.start().69 Starting the CleanShutdown service.
2015-11-16 17:12:42.617 INFO: [20] org.jitsi.service.libjitsi.LibJitsi.info() Successfully started LibJitsi using as implementation: org.jitsi.impl.libjitsi.LibJitsiOSGiImpl
2015-11-16 17:12:42.727 INFO: [20] plugin.defaultresourcepack.DefaultResourcePackActivator.start().104 Default resources ... [REGISTERED]
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.runtime.name=Java(TM) SE Runtime Environment
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() felix.config.properties=file:./lib/felix.client.run.properties
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.boot.library.path=C:\Program Files\Jitsi\jre\bin
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vm.version=25.40-b25
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.java2d.d3d=false
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vm.vendor=Oracle Corporation
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vendor.url=http://java.oracle.com/
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() path.separator=;
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.util.logging.config.file=lib/logging.properties
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vm.name=Java HotSpot(TM) 64-Bit Server VM
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() file.encoding.pkg=sun.io
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() user.country=BR
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() user.script=
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.os.patch.level=
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vm.specification.name=Java Virtual Machine Specification
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() user.dir=C:\Program Files\Jitsi
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.runtime.version=1.8.0_40-b25
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.endorsed.dirs=C:\Program Files\Jitsi\jre\lib\endorsed
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() os.arch=amd64
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.io.tmpdir=C:\Users\rodrigo\AppData\Local\Temp\
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() line.separator=

2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vm.specification.vendor=Oracle Corporation
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() user.variant=
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() os.name=Windows 8
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.jnu.encoding=Cp1252
2015-11-16 17:12:42.789 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.library.path=C:\Program Files\Jitsi\native
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() net.java.sip.communicator.SC_CACHE_DIR_LOCATION=C:\Users\rodrigo\AppData\Local
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.specification.name=Java Platform API Specification
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.class.version=52.0
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() org.jitsi.service.audionotifier.AudioNotifierService=org.jitsi.impl.neomedia.notify.AudioNotifierServiceImpl
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.management.compiler=HotSpot 64-Bit Tiered Compilers
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() os.version=6.2
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() user.home=C:\Users\rodrigo
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() user.timezone=America/Sao_Paulo
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.awt.printerjob=sun.awt.windows.WPrinterJob
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() file.encoding=Cp1252
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.specification.version=1.8
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() jna.library.path=C:\Program Files\Jitsi\native
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.class.path=lib\felix.jar;sc-bundles\sc-launcher.jar;sc-bundles\util.jar;lib
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() user.name=rodrigo
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vm.specification.version=1.8
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.home=C:\Program Files\Jitsi\jre
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.arch.data.model=64
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() user.language=pt
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.specification.vendor=Oracle Corporation
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() awt.toolkit=sun.awt.windows.WToolkit
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vm.info=mixed mode
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.version=1.8.0_40
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.ext.dirs=C:\Program Files\Jitsi\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.boot.class.path=C:\Program Files\Jitsi\jre\lib\resources.jar;C:\Program Files\Jitsi\jre\lib\rt.jar;C:\Program Files\Jitsi\jre\lib\sunrsasign.jar;C:\Program Files\Jitsi\jre\lib\jsse.jar;C:\Program Files\Jitsi\jre\lib\jce.jar;C:\Program Files\Jitsi\jre\lib\charsets.jar;C:\Program Files\Jitsi\jre\lib\jfr.jar;C:\Program Files\Jitsi\jre\classes
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() net.java.sip.communicator.SC_HOME_DIR_LOCATION=C:\Users\rodrigo\AppData\Roaming
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vendor=Oracle Corporation
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() file.separator=\
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() net.java.sip.communicator.SC_HOME_DIR_NAME=Jitsi
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() java.vendor.url.bug=http://bugreport.sun.com/bugreport/
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.io.unicode.encoding=UnicodeLittle
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.cpu.endian=little
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() net.java.sip.communicator.SC_LOG_DIR_LOCATION=C:\Users\rodrigo\AppData\Local
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.desktop=windows
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() sun.cpu.isalist=amd64
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() Normal classloader
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() Normal classloader
2015-11-16 17:12:42.805 INFO: [20] org.jitsi.impl.configuration.ConfigurationServiceImpl.info() failed to find jitsi-default-overrides.properties with class loader, will continue without it.
2015-11-16 17:12:42.867 INFO: [20] impl.resources.ResourceManagementActivator.start().81 Resource manager STARTED
2015-11-16 17:12:42.867 INFO: [20] impl.resources.ResourceManagementActivator.start().90 Resource manager REGISTERED
2015-11-16 17:12:42.898 INFO: [20] service.notification.NotificationServiceActivator.start().48 Notification Service...[  STARTED ]
2015-11-16 17:12:42.898 INFO: [20] service.notification.NotificationServiceActivator.start().55 Notification Service ...[REGISTERED]
2015-11-16 17:12:42.930 INFO: [20] impl.dns.DnsUtilActivator.start().118 DNS service ... [STARTING]
2015-11-16 17:12:42.992 INFO: [20] impl.dns.DnsUtilActivator.start().144 ParallelResolver ... [REGISTERED]
2015-11-16 17:12:42.992 INFO: [20] impl.dns.DnsUtilActivator.start().158 DNS service ... [STARTED]
2015-11-16 17:12:43.023 INFO: [20] impl.netaddr.NetworkAddressManagerServiceImpl.start().92 Network Address Manager         ...[  STARTED ]
2015-11-16 17:12:43.102 INFO: [20] impl.netaddr.NetworkConfigurationWatcher.checkNetworkInterfaces().398 Currently Active eth4:[/192.168.56.1]
2015-11-16 17:12:43.102 INFO: [20] impl.netaddr.NetworkConfigurationWatcher.checkNetworkInterfaces().398 Currently Active eth1:[/192.168.60.100]
2015-11-16 17:12:43.133 INFO: [20] impl.dns.DnsUtilActivator.logDNSServers().293 Loading or Reloading resolver config, default DNS servers are: 192.168.60.1, 
2015-11-16 17:12:43.148 INFO: [20] impl.dns.DnsUtilActivator.logDNSServers().293 Loading or Reloading resolver config, default DNS servers are: 192.168.60.1, 
2015-11-16 17:12:43.180 INFO: [20] impl.netaddr.NetworkAddressManagerServiceImpl.start().98 Network Address Manager Service ...[REGISTERED]
2015-11-16 17:12:43.195 INFO: [20] impl.browserlauncher.BrowserLauncherActivator.start().81 Browser Launcher Service STARTED
2015-11-16 17:12:43.195 INFO: [20] impl.browserlauncher.BrowserLauncherActivator.start().90 Browser Launcher Service REGISTERED
2015-11-16 17:12:43.211 INFO: [20] impl.packetlogging.PacketLoggingActivator.start().100 Packet Logging Service ...[REGISTERED]
2015-11-16 17:12:43.242 INFO: [20] impl.version.VersionActivator.start() Jitsi Version: Jitsi 2.9.5485
2015-11-16 17:12:43.430 INFO: [20] plugin.globalproxyconfig.GlobalProxyPluginActivator.start().90 GLOBAL PROXY CONFIGURATION PLUGIN... [REGISTERED]
2015-11-16 17:12:43.461 INFO: [20] impl.phonenumbers.PhoneNumberServiceActivator.start().48 Packet Logging Service ...[REGISTERED]
2015-11-16 17:12:43.680 INFO: [20] org.jitsi.impl.neomedia.device.DeviceSystem.info() Initializing audio devices
2015-11-16 17:12:43.930 INFO: [20] org.jitsi.impl.neomedia.device.DeviceSystem.info() Initializing video devices
2015-11-16 17:12:43.930 INFO: [20] org.jitsi.impl.neomedia.device.DeviceConfiguration.info() Looking for configured audio devices.
2015-11-16 17:12:43.930 INFO: [20] org.jitsi.impl.neomedia.device.DeviceConfiguration.info() Scanning for configured Video Devices.
2015-11-16 17:12:43.930 INFO: [20] org.jitsi.impl.neomedia.device.DeviceConfiguration.info() Found Desktop Streaming 0 as a AVFRAME, class org.jitsi.impl.neomedia.codec.video.AVFrame video capture device.
2015-11-16 17:12:44.008 INFO: [20] impl.neomedia.NeomediaActivator.start().542 Audio Notifier Service ...[REGISTERED]
2015-11-16 17:12:44.195 INFO: [20] impl.protocol.irc.IrcActivator.start().115 IRC protocol implementation [STARTED].
2015-11-16 17:12:44.539 INFO: [20] impl.msghistory.MessageHistoryActivator.start().102 Message History Service ...[REGISTERED]
2015-11-16 17:12:44.586 INFO: [20] impl.callhistory.CallHistoryActivator.start().101 Call History Service ...[REGISTERED]
2015-11-16 17:12:44.602 INFO: [20] impl.filehistory.FileHistoryActivator.start().73 File History Service ...[REGISTERED]
2015-11-16 17:12:44.617 INFO: [20] impl.metahistory.MetaHistoryActivator.start().67 Meta History Service ...[REGISTERED]
2015-11-16 17:12:44.820 INFO: [20] impl.swingnotification.SwingNotificationActivator.start().63 Swing Notification ...[  STARTING ]
2015-11-16 17:12:44.836 INFO: [20] impl.swingnotification.SwingNotificationActivator.start().79 Swing Notification ...[REGISTERED]
2015-11-16 17:12:44.836 INFO: [20] impl.osdependent.OsDependentActivator.start().170 Systray Service...[  STARTED ]
2015-11-16 17:12:44.852 INFO: [20] impl.osdependent.OsDependentActivator.start().178 Systray Service ...[REGISTERED]
2015-11-16 17:12:44.852 INFO: [20] impl.osdependent.OsDependentActivator.start().184 Desktop Service...[  STARTED ]
2015-11-16 17:12:44.852 INFO: [20] impl.osdependent.OsDependentActivator.start().192 Desktop Service ...[REGISTERED]
2015-11-16 17:12:45.075 INFO: [20] impl.notification.NotificationActivator.start().70 Notification handler Service...[  STARTED ]
2015-11-16 17:12:45.075 INFO: [20] impl.notification.NotificationActivator.start().90 Notification handler Service ...[REGISTERED]
2015-11-16 17:12:45.091 INFO: [20] plugin.notificationwiring.NotificationWiringActivator.start().58 Notification wiring plugin...[  STARTED ]
2015-11-16 17:12:45.231 INFO: [20] plugin.notificationwiring.NotificationWiringActivator.start().70 Notification wiring plugin ...[REGISTERED]
2015-11-16 17:12:45.263 INFO: [20] plugin.contactinfo.ContactInfoActivator.start().116 CONTACT INFO... [REGISTERED]
2015-11-16 17:12:45.372 INFO: [20] plugin.advancedconfig.AdvancedConfigActivator.start().118 ADVANCED CONFIG PLUGIN... [REGISTERED]
2015-11-16 17:12:45.403 INFO: [20] impl.replacement.youtube.YoutubeActivator.start().68 Youtube source implementation [STARTED].
2015-11-16 17:12:45.434 INFO: [20] impl.replacement.dailymotion.DailymotionActivator.start().67 Dailymotion source implementation [STARTED].
2015-11-16 17:12:45.466 INFO: [20] impl.replacement.smiley.SmileyActivator.start().87 Smiley source implementation [STARTED].
2015-11-16 17:12:45.497 INFO: [20] impl.replacement.vimeo.VimeoActivator.start().68 Vimeo source implementation [STARTED].
2015-11-16 17:12:45.534 INFO: [20] impl.replacement.vbox7.Vbox7Activator.start().68 Vbox7 source implementation [STARTED].
2015-11-16 17:12:45.551 INFO: [20] impl.replacement.metacafe.MetacafeActivator.start().69 Metacafe source implementation [STARTED].
2015-11-16 17:12:45.573 INFO: [20] impl.replacement.flickr.FlickrActivator.start().69 Flickr source implementation [STARTED].
2015-11-16 17:12:45.573 INFO: [20] impl.replacement.hulu.HuluActivator.start().68 HULU source implementation [STARTED].
2015-11-16 17:12:45.604 INFO: [20] impl.replacement.twitpic.TwitpicActivator.start().69 Twitpic source implementation [STARTED].
2015-11-16 17:12:45.620 INFO: [20] impl.replacement.directimage.DirectImageActivator.start().88 Direct Image Link source implementation [STARTED].
2015-11-16 17:12:45.636 INFO: [20] impl.replacement.bliptv.BliptvActivator.start().69 Blip.TV source implementation [STARTED].
2015-11-16 17:12:45.651 INFO: [20] impl.replacement.viddler.ViddlerActivator.start().69 Viddler source implementation [STARTED].
2015-11-16 17:12:45.714 INFO: [20] plugin.addrbook.AddrBookActivator.start().241 Address book "plugin.addrbook.ADDRESS_BOOKS" ... [STARTED]
2015-11-16 17:12:45.823 INFO: [400] impl.gui.GuiActivator.run().197 UI Service...[  STARTED ]
2015-11-16 17:12:45.854 INFO: [400] impl.gui.UIServiceImpl.serviceChanged().1085 Handling registration of a new Plugin Component.
2015-11-16 17:12:45.854 INFO: [400] impl.gui.utils.PluginContainer.addPluginComponent().128 Will add plugin component: net.java.sip.communicator.plugin.update.CheckForUpdatesMenuItemComponent@498793b3
2015-11-16 17:12:45.886 INFO: [400] impl.gui.main.account.AccountRegWizardContainerImpl.serviceChanged().363 Handling registration of a new Account Wizard.
2015-11-16 17:12:45.917 INFO: [400] impl.gui.UIServiceImpl.serviceChanged().1085 Handling registration of a new Plugin Component.
2015-11-16 17:12:45.917 INFO: [400] impl.gui.main.account.AccountRegWizardContainerImpl.serviceChanged().363 Handling registration of a new Account Wizard.
2015-11-16 17:12:45.932 INFO: [400] plugin.ircaccregwizz.IrcAccRegWizzActivator.start().60 Loading irc account wizard.
2015-11-16 17:12:45.932 INFO: [400] impl.gui.main.account.AccountRegWizardContainerImpl.serviceChanged().363 Handling registration of a new Account Wizard.
2015-11-16 17:12:45.932 INFO: [400] plugin.ircaccregwizz.IrcAccRegWizzActivator.start().80 IRC account registration wizard [STARTED].
2015-11-16 17:12:45.932 INFO: [400] impl.gui.main.account.AccountRegWizardContainerImpl.serviceChanged().363 Handling registration of a new Account Wizard.
2015-11-16 17:12:45.979 INFO: [20] plugin.addrbook.msoutlook.MsOutlookAddrBookContactSourceService.<clinit>().134 Outlook 2003-x32 is installed.
2015-11-16 17:12:45.979 INFO: [20] plugin.addrbook.msoutlook.MsOutlookAddrBookContactSourceService.initMAPI().202 Init mapi with log level 0 and log file path C:\Users\rodrigo\AppData\Local\Jitsi\log\
2015-11-16 17:12:45.979 INFO: [400] plugin.facebookaccregwizz.FacebookAccRegWizzActivator.start().79 Loading facebook account wizard.
2015-11-16 17:12:45.979 INFO: [400] impl.gui.main.account.AccountRegWizardContainerImpl.serviceChanged().363 Handling registration of a new Account Wizard.
2015-11-16 17:12:45.979 INFO: [400] plugin.facebookaccregwizz.FacebookAccRegWizzActivator.start().101 Facebook account registration wizard [STARTED].
2015-11-16 17:12:45.995 INFO: [400] impl.gui.main.account.AccountRegWizardContainerImpl.serviceChanged().363 Handling registration of a new Account Wizard.
2015-11-16 17:12:45.995 INFO: [400] impl.gui.UIServiceImpl.serviceChanged().1085 Handling registration of a new Plugin Component.
2015-11-16 17:12:45.995 INFO: [400] impl.gui.utils.PluginContainer.addPluginComponent().128 Will add plugin component: net.java.sip.communicator.plugin.branding.AboutWindowPluginComponent@224b35b0
2015-11-16 17:12:46.011 INFO: [400] plugin.branding.BrandingActivator.registerMenuEntryNonMacOSX().249 ABOUT WINDOW ... [REGISTERED]
2015-11-16 17:12:46.011 INFO: [400] impl.gui.UIServiceImpl.serviceChanged().1085 Handling registration of a new Plugin Component.
2015-11-16 17:12:46.011 INFO: [400] plugin.branding.BrandingActivator.registerMenuEntryNonMacOSX().271 CHAT ABOUT WINDOW ... [REGISTERED]
2015-11-16 17:12:46.026 INFO: [400] plugin.advancedconfig.AdvancedConfigurationPanel.serviceChanged().172 Handling registration of a new Configuration Form.
2015-11-16 17:12:46.057 INFO: [400] plugin.advancedconfig.AdvancedConfigurationPanel.serviceChanged().172 Handling registration of a new Configuration Form.
2015-11-16 17:12:46.073 INFO: [400] plugin.advancedconfig.AdvancedConfigurationPanel.serviceChanged().172 Handling registration of a new Configuration Form.
2015-11-16 17:12:46.073 INFO: [400] plugin.advancedconfig.AdvancedConfigurationPanel.serviceChanged().172 Handling registration of a new Configuration Form.
2015-11-16 17:12:46.089 INFO: [400] plugin.generalconfig.GeneralConfigPluginActivator.start().232 PREFERENCES PLUGIN... [REGISTERED]
2015-11-16 17:12:46.089 INFO: [400] impl.gui.main.account.AccountRegWizardContainerImpl.serviceChanged().363 Handling registration of a new Account Wizard.
2015-11-16 17:12:46.120 INFO: [400] impl.gui.UIServiceImpl.serviceChanged().1085 Handling registration of a new Plugin Component.
2015-11-16 17:12:46.120 INFO: [400] impl.gui.UIServiceImpl.serviceChanged().1085 Handling registration of a new Plugin Component.
2015-11-16 17:12:46.136 INFO: [400] impl.gui.UIServiceImpl.serviceChanged().1085 Handling registration of a new Plugin Component.
2015-11-16 17:12:46.214 INFO: [400] impl.gui.UIServiceImpl.serviceChanged().1085 Handling registration of a new Plugin Component.
2015-11-16 17:12:46.229 INFO: [400] impl.gui.main.account.AccountRegWizardContainerImpl.serviceChanged().363 Handling registration of a new Account Wizard.
2015-11-16 17:12:46.464 SEVERE: [223] impl.osdependent.jdic.SystrayServiceJdicImpl.checkInitialized().475 Systray not init
2015-11-16 17:12:46.807 INFO: [402] impl.certificate.CertificateServiceImpl.getTrustManager().682 Using Windows-ROOT. Aliases sucessfully renamed on 72 root certificates.
2015-11-16 17:12:46.807 SEVERE: [402] service.httputil.HttpUtils.openURLConnection().150 Cannot open connection to:https://download.jitsi.org/jitsi/windows/versionupdate.properties
java.lang.ArrayIndexOutOfBoundsException: 0
	at sun.security.mscapi.KeyStore.engineGetCertificate(KeyStore.java:320)
	at sun.security.mscapi.KeyStore$ROOT.engineGetCertificate(KeyStore.java:66)
	at java.security.KeyStore.getCertificate(KeyStore.java:1081)
	at sun.security.validator.KeyStores.getTrustedCerts(KeyStores.java:102)
	at sun.security.ssl.X509TrustManagerImpl.<init>(X509TrustManagerImpl.java:78)
	at sun.security.ssl.TrustManagerFactoryImpl$PKIXFactory.getInstance(TrustManagerFactoryImpl.java:261)
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:78)
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
	at net.java.sip.communicator.impl.certificate.CertificateServiceImpl.getTrustManager(CertificateServiceImpl.java:692)
	at net.java.sip.communicator.impl.certificate.CertificateServiceImpl.getTrustManager(CertificateServiceImpl.java:621)
	at net.java.sip.communicator.service.httputil.HttpUtils.getHttpClient(HttpUtils.java:694)
	at net.java.sip.communicator.service.httputil.HttpUtils.openURLConnection(HttpUtils.java:127)
	at net.java.sip.communicator.service.httputil.HttpUtils.openURLConnection(HttpUtils.java:85)
	at net.java.sip.communicator.plugin.update.UpdateServiceImpl.isLatestVersion(UpdateServiceImpl.java:439)
	at net.java.sip.communicator.plugin.update.UpdateServiceImpl.runInCheckForUpdatesThread(UpdateServiceImpl.java:543)
	at net.java.sip.communicator.plugin.update.UpdateServiceImpl.access$600(UpdateServiceImpl.java:48)
	at net.java.sip.communicator.plugin.update.UpdateServiceImpl$9.run(UpdateServiceImpl.java:1127)
2015-11-16 17:12:47.120 INFO: [400] service.systray.AbstractSystrayService.initHandlers().276 added the following popup handler : None
2015-11-16 17:12:47.120 INFO: [400] service.systray.AbstractSystrayService.initHandlers().276 added the following popup handler : Jitsi popups
2015-11-16 17:12:47.120 INFO: [400] service.systray.AbstractSystrayService.initHandlers().276 added the following popup handler : Systray balloon messages
2015-11-16 17:12:47.120 INFO: [400] service.systray.AbstractSystrayService.setActivePopupMessageHandler().175 setting the following popup handler as active: Jitsi popups
2015-11-16 17:12:47.120 INFO: [400] impl.gui.GuiActivator.run().205 UI Service ...[REGISTERED]
2015-11-16 17:12:47.245 INFO: [408] impl.certificate.CertificateServiceImpl.getTrustManager().682 Using Windows-ROOT. Aliases sucessfully renamed on 72 root certificates.
2015-11-16 17:12:47.245 SEVERE: [408] util.account.LoginManager.run().442 Failed to register protocol provider. 
java.lang.ArrayIndexOutOfBoundsException: 0
	at sun.security.mscapi.KeyStore.engineGetCertificate(KeyStore.java:320)
	at sun.security.mscapi.KeyStore$ROOT.engineGetCertificate(KeyStore.java:66)
	at java.security.KeyStore.getCertificate(KeyStore.java:1081)
	at sun.security.validator.KeyStores.getTrustedCerts(KeyStores.java:102)
	at sun.security.ssl.X509TrustManagerImpl.<init>(X509TrustManagerImpl.java:78)
	at sun.security.ssl.TrustManagerFactoryImpl$PKIXFactory.getInstance(TrustManagerFactoryImpl.java:261)
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:78)
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
	at net.java.sip.communicator.impl.certificate.CertificateServiceImpl.getTrustManager(CertificateServiceImpl.java:692)
	at net.java.sip.communicator.impl.certificate.CertificateServiceImpl.getTrustManager(CertificateServiceImpl.java:604)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.getTrustManager(ProtocolProviderServiceJabberImpl.java:1350)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1157)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:944)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:755)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:468)
	at net.java.sip.communicator.util.account.LoginManager$RegisterProvider.run(LoginManager.java:434)
```

**Comment by ibauersachs** [comment]
Not sure what's going on there, but it's a problem accessing Windows' root certificates. Try accessing https://jitsi.org with Edge, IE or Chrome (not Firefox) and then retry. If that doesn't help you can switch to using Java's root certificates under Tools->Options->Advanced->TLS configuration->Java, but note that this is less secure.

**Comment by rodrigocorsi2** [comment]
Thank you, I changed to use Java certificates and worked well.

**Comment by andre-pelisoli** [comment]
I had the same problem on Windows 8.1 Pro and changing to use Java certificates it worked but I'd like to understand why the problem is happening with Windows-Root certificates.

According to what I noticed in the debugging process an ArrayIndexOutOfBoundsException is thrown in getTrustManager method when the following line is executed:

    tmFactory.init(ks);

Could you help me to understand this issue?

**Comment by ibauersachs** [comment]
The code line you quoted initializes the TrustManager (the Java thing verifying if a certificate is trusted) with a KeyStore (the thing that has all the root certificates). In this case the KeyStore is Windows' trusted roots. The API on Windows is called CAPI for Certificate API, hence the name MSCAPI. But I have no idea why the code in the JRE actually fails. But I know from past experience that this code is brittle (as is a lot in the JRE that accesses native Windows stuff).

**Comment by andre-pelisoli** [comment]
Thanks for the explanation, @ibauersachs.
