### ISSUE TITLE
Call could not be created

### ISSUE THREAD

**Issue by Sataur** [jitsi/jitsi#189]
Hi!
You can get this exception when troubleshooting other PBX issues without microphone present and only when video codec is disabled:
```
SEVERE: [507] impl.protocol.sip.CallPeerMediaHandlerSipImpl.throwOperationFailedException().2565 We couldn't find any active Audio/Video devices and couldn't create a call
SEVERE: [507] impl.protocol.sip.CallPeerSipImpl.throwOperationFailedException().2565 An error occurred while sending invite request
net.java.sip.communicator.service.protocol.OperationFailedException: We couldn't find any active Audio/Video devices and couldn't create a call
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.throwOperationFailedException(ProtocolProviderServiceSipImpl.java:2568)
	at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.createMediaDescriptions(CallPeerMediaHandlerSipImpl.java:371)
	at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.createFirstOffer(CallPeerMediaHandlerSipImpl.java:167)
	at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.createOffer(CallPeerMediaHandlerSipImpl.java:139)
	at net.java.sip.communicator.impl.protocol.sip.CallPeerSipImpl.invite(CallPeerSipImpl.java:1481)
	at net.java.sip.communicator.impl.protocol.sip.CallSipImpl.invite(CallSipImpl.java:535)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createOutgoingCall(OperationSetBasicTelephonySipImpl.java:199)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createCall(OperationSetBasicTelephonySipImpl.java:141)
	at net.java.sip.communicator.service.protocol.media.AbstractOperationSetBasicTelephony.createCall(AbstractOperationSetBasicTelephony.java:122)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.internalCall(CallManager.java:2715)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.access$900(CallManager.java:60)
	at net.java.sip.communicator.impl.gui.main.call.CallManager$CreateCallThread.run(CallManager.java:2596)
SEVERE: [221] util.UtilActivator.uncaughtException().119 An uncaught exception occurred in thread=Thread[AWT-EventQueue-0,6,main] and message was: Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at net.java.sip.communicator.impl.gui.main.call.CallPanel.initializeUserInterfaceHierarchy(CallPanel.java:1548)
	at net.java.sip.communicator.impl.gui.main.call.CallPanel.<init>(CallPanel.java:496)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.openCallContainerIfNecessary(CallManager.java:1335)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.access$200(CallManager.java:60)
	at net.java.sip.communicator.impl.gui.main.call.CallManager$GuiCallListener.outgoingCallCreatedInEventDispatchThread(CallManager.java:198)
	at net.java.sip.communicator.impl.gui.main.call.SwingCallListener.onCallEventInEventDispatchThread(SwingCallListener.java:120)
	at net.java.sip.communicator.impl.gui.main.call.SwingCallListener$1.run(SwingCallListener.java:98)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
SEVERE: [507] impl.gui.main.call.CallManager.run().2609 The call could not be created: 
net.java.sip.communicator.service.protocol.OperationFailedException: An error occurred while sending invite request
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.throwOperationFailedException(ProtocolProviderServiceSipImpl.java:2570)
	at net.java.sip.communicator.impl.protocol.sip.CallPeerSipImpl.invite(CallPeerSipImpl.java:1492)
	at net.java.sip.communicator.impl.protocol.sip.CallSipImpl.invite(CallSipImpl.java:535)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createOutgoingCall(OperationSetBasicTelephonySipImpl.java:199)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createCall(OperationSetBasicTelephonySipImpl.java:141)
	at net.java.sip.communicator.service.protocol.media.AbstractOperationSetBasicTelephony.createCall(AbstractOperationSetBasicTelephony.java:122)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.internalCall(CallManager.java:2715)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.access$900(CallManager.java:60)
	at net.java.sip.communicator.impl.gui.main.call.CallManager$CreateCallThread.run(CallManager.java:2596)
Caused by: net.java.sip.communicator.service.protocol.OperationFailedException: We couldn't find any active Audio/Video devices and couldn't create a call
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.throwOperationFailedException(ProtocolProviderServiceSipImpl.java:2568)
	at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.createMediaDescriptions(CallPeerMediaHandlerSipImpl.java:371)
	at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.createFirstOffer(CallPeerMediaHandlerSipImpl.java:167)
	at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.createOffer(CallPeerMediaHandlerSipImpl.java:139)
	at net.java.sip.communicator.impl.protocol.sip.CallPeerSipImpl.invite(CallPeerSipImpl.java:1481)
	... 7 more
```

**Comment by ibauersachs** [comment]
You cannot call without a microphone, so this isn't an issue.

**Comment by Sataur** [comment]
It is issue when testing or only checking voice mail? Call will be rejected when video codec enabled...
