### ISSUE TITLE
NullPointerException / NumberFormatException

### ISSUE THREAD

**Issue by bufka** [jitsi/jitsi#191]
When i start jitsi via terminal, i see two exceptions:

```java
08:03:31.125 SCHWERWIEGEND: [32] impl.protocol.jabber.OperationSetPersistentPresenceJabberImpl.initializePriorities().2047 Wrong value for resource priority
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at net.java.sip.communicator.impl.protocol.jabber.OperationSetPersistentPresenceJabberImpl.initializePriorities(OperationSetPersistentPresenceJabberImpl.java:2040)
	at net.java.sip.communicator.impl.protocol.jabber.OperationSetPersistentPresenceJabberImpl.<init>(OperationSetPersistentPresenceJabberImpl.java:146)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initialize(ProtocolProviderServiceJabberImpl.java:1598)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderFactoryJabberImpl.createService(ProtocolProviderFactoryJabberImpl.java:137)
	at net.java.sip.communicator.service.protocol.ProtocolProviderFactory.loadAccount(ProtocolProviderFactory.java:978)
	at net.java.sip.communicator.service.protocol.AccountManager.doLoadStoredAccounts(AccountManager.java:204)
	at net.java.sip.communicator.service.protocol.AccountManager.loadStoredAccounts(AccountManager.java:446)
	at net.java.sip.communicator.service.protocol.AccountManager.runInLoadStoredAccountsThread(AccountManager.java:562)
	at net.java.sip.communicator.service.protocol.AccountManager.access$100(AccountManager.java:26)
	at net.java.sip.communicator.service.protocol.AccountManager$2.run(AccountManager.java:487)
java.lang.NullPointerException
	at net.java.sip.communicator.plugin.pluginmanager.PluginManagerActivator.start(PluginManagerActivator.java:86)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2152)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2070)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1297)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Thread.java:745)
```

Jitsi is working fine after that...its not critical.

Here some info about the system:

* OS: 4.1.12-1-MANJARO
* Java: 
    * openjdk version "1.8.0_65"
    * OpenJDK Runtime Environment (build 1.8.0_65-b17)
    * OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
* Jitsi: 2.8.build.2.8.5426

**Comment by ibauersachs** [comment]
The resource priority is something that is set in the options of your XMPP account (Tools->Options->Accounts->your account->Connection->Resource). Normally this is set automatically, but just enter a random value for priority, e.g. 30.
If generate automatically is set, uncheck it, set a name and priority, save (and optionally enable automatic generation again).

**Comment by bufka** [comment]
Done! But now i get another NullPointer

<pre>java.lang.NullPointerException
	at net.java.sip.communicator.plugin.pluginmanager.PluginManagerActivator.start(PluginManagerActivator.java:86)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2152)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2070)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1297)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by ibauersachs** [comment]
Is that a build from source or some custom package (potentially using improperly packaged system libraries)?

**Comment by bufka** [comment]
Installed via AUR...that explains (maybe) the exception :)

**Comment by ibauersachs** [comment]
I'm sorry, but we're lacking resources to support that (we're short on help for anything else too).

**Comment by bufka** [comment]
No problem, its not a critical...

**Comment by ibauersachs** [comment]
The first message about an NPE can be complety ignored. If there's no value defined in the account properties, the default of 30 is used.
The second message is likely because of the AUR packaging and harmless, although it likely makes the plugin manager plugin unusable (but there aren't really any external plugins available for Jitsi, so...).
