### ISSUE TITLE
Calling sip number fails. 

### ISSUE THREAD

**Issue by dareni** [jitsi/jitsi#230]
Debian 8.1
Linux sweetpea 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux

$ java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)

Jitsi version: 2.8.5426

Dialing the 775 information number 775@sip.pennytel.com gives the error:

10:11:05.066 SEVERE: [187] service.protocol.media.MediaAwareCallPeer.logAndFail().684 Remote party sent a faulty session description.
java.lang.IllegalArgumentException: No "c=" field in the following media description nor in the enclosing session:
m=video 0 RTP/AVP 97^M

    at net.java.sip.communicator.impl.protocol.sip.sdp.SdpUtils.extractDefaultTarget(SdpUtils.java:895)
    at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.doNonSynchronisedProcessAnswer(CallPeerMediaHandlerSipImpl.java:1422)
    at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.processAnswer(CallPeerMediaHandlerSipImpl.java:1371)
    at net.java.sip.communicator.impl.protocol.sip.CallPeerMediaHandlerSipImpl.processAnswer(CallPeerMediaHandlerSipImpl.java:1345)
    at net.java.sip.communicator.impl.protocol.sip.CallPeerSipImpl.processInviteOK(CallPeerSipImpl.java:811)
    at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.processInviteOK(OperationSetBasicTelephonySipImpl.java:818)
    at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.processResponse(OperationSetBasicTelephonySipImpl.java:441)
    at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.processResponse(ProtocolProviderServiceSipImpl.java:737)
    at net.java.sip.communicator.impl.protocol.sip.SipStackSharing.processResponse(SipStackSharing.java:751)
    at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:296)
    at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:196)
    at gov.nist.javax.sip.DialogFilter.processResponse(DialogFilter.java:1480)
    at gov.nist.javax.sip.stack.SIPClientTransaction.inviteClientTransaction(SIPClientTransaction.java:885)
    at gov.nist.javax.sip.stack.SIPClientTransaction.processResponse(SIPClientTransaction.java:548)
    at gov.nist.javax.sip.stack.SIPClientTransaction.processResponse(SIPClientTransaction.java:1554)
    at gov.nist.javax.sip.stack.UDPMessageChannel.processMessage(UDPMessageChannel.java:583)
    at gov.nist.javax.sip.stack.UDPMessageChannel.processIncomingDataPacket(UDPMessageChannel.java:492)
    at gov.nist.javax.sip.stack.UDPMessageChannel.run(UDPMessageChannel.java:297)
    at java.lang.Thread.run(Thread.java:745)

To recreate the error create a free account at www.pennytel.com setup the sip account in jitsi and dial the 775 information number.

**Comment by ibauersachs** [comment]
Please check https://jitsi.org/faq/frag

**Comment by dareni** [comment]
Thanks - disabling the video encodings fixed the problem and the call is successful.
