### ISSUE TITLE
Google contacts

### ISSUE THREAD

**Issue by fumantsu** [jitsi/jitsi#259]
Good day,

I'm also one who is facing issues with Google Contacts. I don't getting the popup for the extra authentication. From the logs I have this.
```
17:29:48.482 INFO: [239] impl.googlecontacts.GoogleContactsConnectionImpl.connect().132 Google contacts connection failure: com.google.gdata.util.AuthenticationException: Error authenticating (check service name)
17:29:48.551 INFO: [239] impl.googlecontacts.GoogleContactsServiceImpl.searchContact().277 Problem occurred during Google Contacts retrievment
java.lang.NullPointerException: No authentication header information
	at com.google.gdata.util.AuthenticationException.initFromAuthHeader(AuthenticationException.java:96)
	at com.google.gdata.util.AuthenticationException.<init>(AuthenticationException.java:67)
	at com.google.gdata.client.http.HttpGDataRequest.handleErrorResponse(HttpGDataRequest.java:600)
	at com.google.gdata.client.http.GoogleGDataRequest.handleErrorResponse(GoogleGDataRequest.java:563)
	at com.google.gdata.client.http.HttpGDataRequest.checkResponse(HttpGDataRequest.java:552)
	at com.google.gdata.client.http.HttpGDataRequest.execute(HttpGDataRequest.java:530)
	at com.google.gdata.client.http.GoogleGDataRequest.execute(GoogleGDataRequest.java:535)
	at com.google.gdata.client.Service.getFeed(Service.java:1135)
	at com.google.gdata.client.Service.getFeed(Service.java:1077)
	at com.google.gdata.client.GoogleService.getFeed(GoogleService.java:662)
	at com.google.gdata.client.Service.query(Service.java:1237)
	at com.google.gdata.client.Service.query(Service.java:1178)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsServiceImpl.searchContact(GoogleContactsServiceImpl.java:272)
	at net.java.sip.communicator.impl.googlecontacts.GoogleContactsQuery.run(GoogleContactsQuery.java:125)
	at net.java.sip.communicator.service.contactsource.AsyncContactQuery$1.run(AsyncContactQuery.java:314)
```

I'm using the latest stable Windows version (Win10) and important, I have 2 way authentication.

**Comment by jitsi-developers** [comment]
try latest nightly, as far as I remember it was implemented in nightly
build some time ago.

**Comment by fumantsu** [comment]
It works. Is any way (or plan) to be visible permanently as some kind of group?

**Comment by ibauersachs** [comment]
No.
