### ISSUE TITLE
java.lang.IllegalArgumentException: invalid transport

### ISSUE THREAD

**Issue by radius314** [jitsi/jitsi#280]
Getting this error periodically on macos 10.12 Sierra.  After running a few successful calls, I get this error.  I have to close it out and re-open to resolve.

Running jitsi nightly 2.9.5522

 ```
java.lang.IllegalArgumentException: invalid transport
	at net.java.sip.communicator.impl.protocol.sip.SipStackSharing.getJainSipProvider(SipStackSharing.java:485)
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getJainSipProvider(ProtocolProviderServiceSipImpl.java:1689)
	at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.getDefaultJainSipProvider(ProtocolProviderServiceSipImpl.java:2068)
	at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createInviteRequest(SipMessageFactory.java:738)
	at net.java.sip.communicator.impl.protocol.sip.SipMessageFactory.createInviteRequest(SipMessageFactory.java:878)
	at net.java.sip.communicator.impl.protocol.sip.CallSipImpl.invite(CallSipImpl.java:464)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createOutgoingCall(OperationSetBasicTelephonySipImpl.java:199)
	at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicTelephonySipImpl.createCall(OperationSetBasicTelephonySipImpl.java:141)
	at net.java.sip.communicator.service.protocol.media.AbstractOperationSetBasicTelephony.createCall(AbstractOperationSetBasicTelephony.java:122)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.internalCall(CallManager.java:2715)
	at net.java.sip.communicator.impl.gui.main.call.CallManager.access$900(CallManager.java:60)
	at net.java.sip.communicator.impl.gui.main.call.CallManager$CreateCallThread.run(CallManager.java:2596)
```

**Comment by ibauersachs** [comment]
Please send your entire [logs](https://jitsi.org/logs) to the dev [mailing list](http://lists.jitsi.org) when the issue has occurred again.
We also need to know which SIP provider or server you're using. Does this happen after you resume from standby, etc.?
