### ISSUE TITLE
Jitsi crashes on incoming call - ubuntu 14.04 64 bit

### ISSUE THREAD

**Issue by mail2vijay** [jitsi/jitsi#296]
I installed jitsi from ubuntu package 2.8 but it throws exceptions on incoming call with no sound.
Exception Detail

```
SEVERE: [555] util.UtilActivator.uncaughtException().119 An uncaught exception occurred in thread=Thread[org.jitsi.impl.neomedia.protocol.PushBufferDataSourceAdapter$PushBufferStreamAdapter.streamReadThread,5,system] and message was: null
java.lang.reflect.UndeclaredThrowableException
    at org.jitsi.impl.neomedia.conference.AudioMixerPushBufferStream.transferData(AudioMixerPushBufferStream.java:1179)
    at org.jitsi.impl.neomedia.conference.AudioMixerPushBufferStream$1.transferData(AudioMixerPushBufferStream.java:133)
    at org.jitsi.impl.neomedia.protocol.StreamSubstituteBufferTransferHandler.transferData(StreamSubstituteBufferTransferHandler.java:91)
    at org.jitsi.impl.neomedia.protocol.PushBufferDataSourceAdapter$PushBufferStreamAdapter.runInStreamReadThread(PushBufferDataSourceAdapter.java:287)
    at org.jitsi.impl.neomedia.protocol.PushBufferDataSourceAdapter$PushBufferStreamAdapter.access$400(PushBufferDataSourceAdapter.java:44)
    at org.jitsi.impl.neomedia.protocol.PushBufferDataSourceAdapter$PushBufferStreamAdapter$1.run(PushBufferDataSourceAdapter.java:343)
Caused by: java.io.IOException
    at org.jitsi.impl.neomedia.protocol.CachingPushBufferStream.read(CachingPushBufferStream.java:394)
    at org.jitsi.impl.neomedia.conference.AudioMixer.read(AudioMixer.java:1012)
    at org.jitsi.impl.neomedia.device.AudioMixerMediaDevice$2.read(AudioMixerMediaDevice.java:332)
    at org.jitsi.impl.neomedia.conference.AudioMixerPushBufferStream.readInPushBufferStream(AudioMixerPushBufferStream.java:595)
    at org.jitsi.impl.neomedia.conference.AudioMixerPushBufferStream.readInPushBufferStreams(AudioMixerPushBufferStream.java:788)
    at org.jitsi.impl.neomedia.conference.AudioMixerPushBufferStream.read(AudioMixerPushBufferStream.java:466)
    at org.jitsi.impl.neomedia.conference.AudioMixerPushBufferStream.transferData(AudioMixerPushBufferStream.java:1175)
    ... 5 more
Caused by: java.io.IOException: The source stream is closed
    at net.sf.fmj.media.multiplexer.RawBufferMux$RawBufferSourceStream.read(RawBufferMux.java:256)
    at org.jitsi.impl.neomedia.protocol.CachingPushBufferStream.transferData(CachingPushBufferStream.java:665)
    at org.jitsi.impl.neomedia.protocol.CachingPushBufferStream$1.transferData(CachingPushBufferStream.java:580)
    at net.sf.fmj.media.multiplexer.RawBufferMux$RawBufferSourceStream.run(RawBufferMux.java:380)
    at java.lang.Thread.run(Thread.java:745)
    at net.sf.fmj.media.util.MediaThread.run(MediaThread.java:202)
```

**Comment by ibauersachs** [comment]
This isn't enough information, we'd need you complete [logs](https://jitsi.org/logs).
