### ISSUE TITLE
Login with Google caused NoClassDefFoundError

### ISSUE THREAD

**Issue by bufka** [jitsi/jitsi#335]
Login with google account is not possible (with icq works fine), i get following exception:

```2017-02-28 18:53:51.333 SCHWERWIEGEND: [538] util.account.LoginManager.run().442 Failed to register protocol provider. 
java.lang.NoClassDefFoundError: org/xbill/DNS/TextParseException
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:731)
	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:478)
	at net.java.sip.communicator.util.account.LoginManager$RegisterProvider.run(LoginManager.java:434)
Caused by: java.lang.ClassNotFoundException: org.xbill.DNS.TextParseException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:1010)
	at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1595)
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1525)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)```

**Comment by ibauersachs** [comment]
In your original comment, you stated Jitsi 2.10.5550 on Linux, but is this the official build from Jitsi or some custom build from your distro?
