### ISSUE TITLE
NullPointerException on startup

### ISSUE THREAD

**Issue by Dalmat** [jitsi/jitsi#357]
Jitsi fails to start on Windows XP due to this NullPointerException :
`C:\Documents and Settings\Maman>java.lang.NullPointerException at net.java.sip.communicator.util.ConfigurationUtils.isPinnedToTaskBar(ConfigurationUtils.java:988)
        at net.java.sip.communicator.util.ConfigurationUtils.loadGuiConfigurations(ConfigurationUtils.java:481)
        at net.java.sip.communicator.impl.gui.GuiActivator.start(GuiActivator.java:159)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2226)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:745)
`

A quick look at the [code ](https://github.com/jitsi/jitsi/blob/master/src/net/java/sip/communicator/util/ConfigurationUtils.java#L988) makes me think that the code fails in case the directory %appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar does not exist.
I had to manually create the directory to make jitsi start.
Failing to do so will never show up the widget.

Could you please properly handle the case of missing directory ?
Thanks

**Comment by jitsi-developers** [comment]
You are still using the windows xp.FYI the support is discontinued by
Microsoft.

**Comment by ibauersachs** [comment]
Windows XP is no longer supported. Please get rid of it (update to a Microsoft-supported Windows or switch to Linux).

**Comment by lmojzis** [comment]
I believe you should really read what the problem is. The program works fine unless %appdata%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar does
 not exist. This error can be reproduced even on Windows 7. The OS version is irrelevant.

**Comment by Dalmat** [comment]
Basically, the spotted issue is about calling methods on a potentially null instance. 
Whatever the cause, the object should be checked imho.

This issue is all the more problematic that there is no notification given to the user, and the program fails silently.

**Comment by ibauersachs** [comment]
I'll look at this as it's probably also causing (or is related to) issues #321 and #342. 

Windows XP still will not be supported anymore.
