### ISSUE TITLE
latest build, no video call point to point call

### ISSUE THREAD

**Issue by emilianoOlivier** [jitsi/jitsi#378]
compile from source or fresh installed latest build ( https://download.jitsi.org/jitsi/nightly/windows/ build5582), video camera is detected correclty in tools-options-video-devices.

Point to point single call between 2 jitsi client (build 5582), audio g711 work well, but video h264 don't show in any client.
I have the same SIP  pbx and used since 2 year jitsi client in old build all work well (all sdp pacadge  are correct), updating to latest built there isn't video. the log show many similar error of this type:

2017-07-17 11:20:09.986 SEVERE: [360] org.jitsi.impl.neomedia.transform.SinglePacketTransformer.log() Failed to reverse-transform RawPacket(s)!
java.lang.IllegalArgumentException: Impossible Exception
        at net.sf.fmj.media.rtp.RTCPPacketParser.parse(RTCPPacketParser.java:441)
        at org.jitsi.impl.neomedia.rtcp.RTCPPacketParserEx.parse(RTCPPacketParserEx.java:80)
        at org.jitsi.impl.neomedia.transform.rtcp.StatisticsEngine.reverseTransform(StatisticsEngine.java:898)
        at org.jitsi.impl.neomedia.transform.SinglePacketTransformer.reverseTransform(SinglePacketTransformer.java:136)
        at org.jitsi.impl.neomedia.transform.TransformEngineChain$PacketTransformerChain.reverseTransform(TransformEngineChain.java:381)
        at org.jitsi.impl.neomedia.transform.TransformInputStream.createRawPacket(TransformInputStream.java:85)
        at org.jitsi.impl.neomedia.RTPConnectorInputStream.runInReceiveThread(RTPConnectorInputStream.java:768)
        at org.jitsi.impl.neomedia.RTPConnectorInputStream.access$000(RTPConnectorInputStream.java:42)
        at org.jitsi.impl.neomedia.RTPConnectorInputStream$3.run(RTPConnectorInputStream.java:565)
2017-07-17 11:20:09.987 SEVERE: [360] org.jitsi.impl.neomedia.RTPConnectorInputStream.log() Failed to receive a packet:
java.lang.IllegalArgumentException: Impossible Exception
        at net.sf.fmj.media.rtp.RTCPPacketParser.parse(RTCPPacketParser.java:441)
        at org.jitsi.impl.neomedia.rtcp.RTCPPacketParserEx.parse(RTCPPacketParserEx.java:80)
        at org.jitsi.impl.neomedia.transform.rtcp.StatisticsEngine.reverseTransform(StatisticsEngine.java:898)
        at org.jitsi.impl.neomedia.transform.SinglePacketTransformer.reverseTransform(SinglePacketTransformer.java:136)
        at org.jitsi.impl.neomedia.transform.TransformEngineChain$PacketTransformerChain.reverseTransform(TransformEngineChain.java:381)
        at org.jitsi.impl.neomedia.transform.TransformInputStream.createRawPacket(TransformInputStream.java:85)
        at org.jitsi.impl.neomedia.RTPConnectorInputStream.runInReceiveThread(RTPConnectorInputStream.java:768)
        at org.jitsi.impl.neomedia.RTPConnectorInputStream.access$000(RTPConnectorInputStream.java:42)
        at org.jitsi.impl.neomedia.RTPConnectorInputStream$3.run(RTPConnectorInputStream.java:565)
2017-07-17 11:20:10.694 INFO: [80] impl.protocol.sip.ProxyRouter.getNextHop().167 Outbound proxy mode, using proxy 10.0.80.10:5060/UDP as hop instead

**Comment by emilianoOlivier** [comment]
i have attacked a simple pcap for the call (direclty from log folder of jitsi), the 10.0.80.10 is my sip proxy for sip message, the 10.1.10.49 and 10.1.10.63 are my jitsi client.
[jitsi0.zip](https://github.com/jitsi/jitsi/files/1152165/jitsi0.zip)

**Comment by emilianoOlivier** [comment]
I can confirm that in Jitsi build  for tag 5550 (stable build) and libjisti corresponding version
1.0-20170201.212655-235 (tag  925) the video call is working.

**Comment by ibauersachs** [comment]
Bug found, the fix is pending the merge of jitsi/libjitsi#342.
