### ISSUE TITLE
Jitsi does not start on a fresh Fedora 28 install

### ISSUE THREAD

**Issue by Af0x** [jitsi/jitsi#480]
Hello,
I set up a fresh Fedora 28 and installed Jitsi from the rpm-packages (nightly, Version 2.11-5602). When trying to start, nothing happens.
Regards,
Af0x

**Comment by Af0x** [comment]
I ran Jitsi on commandline and got this:

> java.awt.HeadlessException
	at java.awt.SplashScreen.getSplashScreen(SplashScreen.java:117)
	at net.java.sip.communicator.impl.splashscreen.SplashScreenActivator.start(SplashScreenActivator.java:70)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
2018-05-18 17:49:34.931 SCHWERWIEGEND: [16] org.jitsi.impl.neomedia.device.DeviceConfiguration.log() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer with JMF.
java.lang.UnsatisfiedLinkError: /tmp/jna-3649/jna1969430243426767306.tmp: libjawt.so: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.jitsi.util.JNIUtils.loadLibrary(JNIUtils.java:104)
	at org.jitsi.util.JNIUtils.loadLibrary(JNIUtils.java:40)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer.<clinit>(JAWTRenderer.java:99)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1046)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:365)
	at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:160)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
	at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
	at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:95)
	at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:172)
	at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:124)
	at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:391)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
2018-05-18 17:49:35.273 SCHWERWIEGEND: [16] impl.osdependent.systemtray.SystemTray.getDefaultDesktop().74 Failed to initialize the java.awt.SystemTray implementation.
java.lang.UnsupportedOperationException: java.lang.reflect.InvocationTargetException
	at net.java.sip.communicator.impl.osdependent.Desktop$AWTDesktopPeer.<init>(Desktop.java:192)
	at net.java.sip.communicator.impl.osdependent.Desktop.getDefaultDesktop(Desktop.java:70)
	at net.java.sip.communicator.impl.osdependent.DesktopServiceImpl.<init>(DesktopServiceImpl.java:41)
	at net.java.sip.communicator.impl.osdependent.OsDependentActivator.start(OsDependentActivator.java:181)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.java.sip.communicator.impl.osdependent.Desktop$AWTDesktopPeer.<init>(Desktop.java:184)
	... 9 more
Caused by: java.awt.HeadlessException
	at java.awt.Desktop.getDesktop(Desktop.java:142)
	... 14 more
2018-05-18 17:49:35.284 SCHWERWIEGEND: [16] impl.osdependent.systemtray.SystemTray.getDefaultDesktop().82 Failed to initialize the desktop.tray implementation.
java.lang.UnsupportedOperationException: Failed to initialize the desktop.tray implementation.
	at net.java.sip.communicator.impl.osdependent.Desktop.getDefaultDesktop(Desktop.java:84)
	at net.java.sip.communicator.impl.osdependent.DesktopServiceImpl.<init>(DesktopServiceImpl.java:41)
	at net.java.sip.communicator.impl.osdependent.OsDependentActivator.start(OsDependentActivator.java:181)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
2018-05-18 17:49:35.318 SCHWERWIEGEND: [37] util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[AWT-EventQueue-0,6,main] and message was: null
java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at net.java.sip.communicator.plugin.desktoputil.SIPCommFrame.<init>(SIPCommFrame.java:100)
	at net.java.sip.communicator.impl.gui.main.MainFrame.<init>(MainFrame.java:191)
	at net.java.sip.communicator.impl.gui.UIServiceImpl.loadApplicationGui(UIServiceImpl.java:161)
	at net.java.sip.communicator.impl.gui.GuiActivator$1.run(GuiActivator.java:182)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.UnsatisfiedLinkError: no jawt in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.jdesktop.jdic.misc.impl.LinuxAlerter.<init>(LinuxAlerter.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jdesktop.jdic.misc.Alerter.loadLinux(Unknown Source)
	at org.jdesktop.jdic.misc.Alerter.newInstance(Unknown Source)
	at net.java.sip.communicator.plugin.chatalerter.ChatAlerterActivator.start(ChatAlerterActivator.java:99)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Af0x** [comment]
hello, thank you for the answer. Is there any way to fix this?

**Comment by ibauersachs** [comment]
@gpolitis We don't even build RPMs anymore and will drop the support entirely for the foreseeable future. With Suse, Red Hat, Fedora and Centos all using different names for the same package(s), one single RPM will always be broken on at least one of the distros.

If we'd manage to move to containerized builds, we might be able to bring it back.

@Af0x make sure you have the full openjdk installed. No idea which package this is on Fedora, on Ubuntu or Debian this would be  `sudo apt install openjdk-8-jre`.

**Comment by Af0x** [comment]
if there will be no more rpm packages, what would be the best way to install it on all the different Linux Distros? And how to update these?

**Comment by jitsi-developers** [comment]
Hi,

I’ve set 1 as a maximum number of lastN.

In the speaker client I want to show as big video the image of the speaker. Usually it is on the top right corner.

Is it possible to manage this kind of situation?

Thank you very much

Angelo

**Comment by ibauersachs** [comment]
Running from source or using a Debian-based distro will be the only solution for the time being.

**Comment by Af0x** [comment]
ok, serious question: after the first installation from source, how do I update this installation? I always use packages and this would be the first time I am going for the source.

**Comment by Af0x** [comment]
furthermore: is there any guide on how to install jitsi from source?

**Comment by ibauersachs** [comment]
You'd basically clone this repo with git, then start Jitsi with `ant run`. Updating is simply `git pull`.
However I should note that this obviously isn't for the faint-hearted, and you need some of the development dependencies installed (namely the JDK and Ant).

**Comment by Af0x** [comment]
I wish you could think again about this decision with the rpm-Repository as this really is the easiest way to install and update (although having sometimes missing package-issues).
Btw: I think the missing package in this issue was "java-1.8.0-openjdk.x86_64".

**Comment by Af0x** [comment]
if I managed to successfully run 
> ant run

Is there any way to make this a clickable file so that the terminal doesn´t need to be open to start Jitsi?

**Comment by jitsi-developers** [comment]
Sure.  Just create a shell script (for example 'run-jitsi'):

    #!/bin/sh
    ant run >/tmp/jitsi.log 2>&1

make it executable (chmod +x run-jitsi), and then you ought to be able to
run that from your desktop.

The bit after the 'ant run' sends all output to a log file called
/tmp/jitsi.log - you may want a better logging solution.

This is all rather more suited to superuser.com/unix.stackexchange.com than
the jitsi mailing list.

Martin

**Comment by Af0x** [comment]
hi, thank you. Unfortunately it´s not working. I tried something like this before and wouldn´t have asked and rather posted the solution.

**Comment by gpolitis** [comment]
Also, depending on your desktop manager, you may have the option to use [desktop files](https://developer.gnome.org/integration-guide/stable/desktop-files.html.en) with the script that Martin posted.

**Comment by Af0x** [comment]
thank you so much, I made it work with this hint and changing the script to first cd into the jitsi directory like the following:
> #!/bin/sh
cd ~/jitsi && ant run

Am I correct that if there are multiple users on one system and I want them all to use Jitsi, I have to clone it for every user to its home directory or is there any possibility to only need one installation that every user can access?

**Comment by tortugaverde98** [comment]
I had the same problem as OP. I ran dnf install java-1.8.0-openjdk.

It responded that it would install openjkd and upgrade openjdk-headless.

It launched fine after that. I also concur with the OP that the jitsi project should not orphan rpm for fedora. Is fedora really that unpopular in comparison to debian?

**Comment by ibauersachs** [comment]
It's not about Fedora in particular, it's about all RPM-based distros (see https://github.com/jitsi/jitsi/issues/480#issuecomment-392033209). It's unpopular for everyone at Jitsi. Feel free to contribute though...

**Comment by Af0x** [comment]
one more question regarding the update process of a git-installation: if I do `git pull`, do I also have to run `ant rebuild` like after installation?

**Comment by ibauersachs** [comment]
`ant make` is usually sufficient. rebuild cleans everything and builds from scratch.

**Comment by CRCinAU** [comment]
While this is probably an older issue, not supporting the biggest enterprise distro is a silly idea.

There is a *massive* market in CentOS and RHEL directly that the "rpms are hard" attitude alienates.

If you force a 'download and run the source' approach, then this should at least be documented. If the RPMs are depreciated, then put a note that says so. I was following the documentation for RPM builds until I realised that the last package built was 18+ months ago.

**Comment by ibauersachs** [comment]
Which market? The one that brings contributors? I don't have access to the webserver with the download pages to add a note. @damencho?

Note that the last stable release has been 18+ months for all distros. The builds of the master branch are more up to date for Debian-packages.

**Comment by CRCinAU** [comment]
Well, hopefully. I've been packaging for RHEL for about a decade and have my own build infrastructure based on mock with CI available - but I can't seem to find anything related to building.

I'm not 100% up to speed with java stuff - but even hints on the existing spec, or even a build from source may help.

I also wonder if distribution of binary tarballs is possible - other projects such as bitbucket / keycloak (which we run clustered) etc seem to have a method of extracting and running - which may suit.

I guess the end goal for me personally is to throw together a jitsi-meet server based on CentOS 7 - as this is our SOE for 50+ systems - and probably others.

**Comment by saghul** [comment]
> I guess the end goal for me personally is to throw together a jitsi-meet server based on CentOS 7 - as this is our SOE for 50+ systems - and probably others.

I think you are in the wrong repo then. This is the Jitsi desktop client, Jitsi Meet is a different project.
