### ISSUE TITLE
Creating and moving contacts to group issues

### ISSUE THREAD

**Issue by Af0x** [jitsi/jitsi#485]
Hello,

I have the following issues with the grouping functionality:
Lets say you have 2 contacts in your list (one SIP and one XMPP, both named the same).
You create a group "SIP" and move the SIP contact into it. No issue. Then you create another Group "XMPP" and try to move the XMPP-contact into it. Not possible.

Then you try to delete the empty group "XMPP" and Jitsi gives you "NULL".

Regards,

Af0x

**Comment by Af0x** [comment]
some excerpt when trying to move the contact to the second group:

> [java] 2018-05-28 17:50:00.336 SCHWERWIEGEND: [703] 
> util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[Thread-73,6,main] and message was: failed to create contact group test-1
>      [java] net.java.sip.communicator.service.contactlist.MetaContactListException: failed to create contact group test-1
>      [java] at net.java.sip.communicator.impl.contactlist.MetaContactListServiceImpl.moveMetaContact(MetaContactListServiceImpl.java:1306)
>      [java] at net.java.sip.communicator.impl.gui.main.contactlist.MetaContactListManager$MoveMetaContactThread.run(MetaContactListManager.java:379)
