### ISSUE TITLE
jitsi not working with java 10

### ISSUE THREAD

**Issue by callegar** [jitsi/jitsi#530]
Verified on ubuntu bionic.

## Description

when the java runtime environment is openjdk 10 (which is the default in bionic, even though bionic is expected to transition to openjdk 11 soon), jitsi fails.

---

## Current behavior

launching jitsi gets you the following error message:

```
Exception in thread "main" java.lang.NoSuchFieldError: preferIPv6Address
        at java.base/java.net.InetAddress.init(Native Method)
        at java.base/java.net.InetAddress.<clinit>(InetAddress.java:337)
        at java.base/java.net.NetworkInterface.init(Native Method)
        at java.base/java.net.NetworkInterface.<clinit>(NetworkInterface.java:68)
        at net.java.sip.communicator.util.launchutils.SipCommunicatorLock.findLocalAddress(SipCommunicatorLock.java:513)
        at net.java.sip.communicator.util.launchutils.SipCommunicatorLock.readLockFile(SipCommunicatorLock.java:413)
        at net.java.sip.communicator.util.launchutils.SipCommunicatorLock.readLockFileRetrying(SipCommunicatorLock.java:358)
        at net.java.sip.communicator.util.launchutils.SipCommunicatorLock.tryLock(SipCommunicatorLock.java:154)
        at net.java.sip.communicator.launcher.SIPCommunicator.main(SIPCommunicator.java:139)
```

---

## Expected Behavior

jitsi should either work fine on openjdk 10 or avoid to pick openjdk 10 as an acceptable jre.

---

## Possible Solution

I believe there are two possible solutions here.

1. This is the long term solution. Make jitsi work correctly with openjdk 10 and 11.
2. Interim solution (that should anyway be adopted IMHO). Modify the jitsi startup script.   Currently the shell script used to start jitsi includes the following item:
```
javabin=`which java`
```
This should be modified to let the jre be chosen via a shell variable (e.g. JITSI_JRE), defaulting to the one found by `which java` only if the shell variable is not configured. The rationale is the following. In the current situtation, to run jitsi, you need either to change the default jre for the whole of your system (via the ubuntu/debian alternatives mechanism) or manually edit the jitsi startup script. Either thing is inconvenient. The second one is inconvenient because whenever jitsi is updated, you need to re-edit the shell script. By having a shell variable, you could configure jitsi to use a suitable jre without touching the rest of your system.

---

## Steps to reproduce

Install the jitsi deb on an ubuntu bionic system which is configured to use the default jre for that distro and launch jitsi.

---

**Comment by ibauersachs** [comment]
This particular problem is a bug in Java itself rather than in Jitsi. The native InetAddress code tries to access a field declared in Java, `preferIPv6Address`.
It's not something we can fix. We're only using documented and supported API here.

**Comment by callegar** [comment]
Still, can the jitsi shell script used for invocation be updated as suggested in point 2 at the "possible solution" paragraph of the bug report? At least that would let one work around the java issue.
Should I open a more specific issue for that?

**Comment by ibauersachs** [comment]
If you're savvy enough to make these modifications, why don't you create a pull request? I'd be happy to include an option for an environment variable that overrides the default Java.

Please also consider reporting the Java bug you encoutered with Ubuntu or the OpenJDK project.
