### ISSUE TITLE
Jitsi Desktop don't started (Windows 10)

### ISSUE THREAD

**Issue by MissRen** [jitsi/jitsi#590]
For some days  I have the problem that Jitsi desktop doesn't start any more. Checks event viewer of Windows at the, I am told that it is compatible for Windows 8.  I already have installed the newer version but it simply doesn't run any more.
 My Windows computer  Windows 10 runs and Java version installed this one on Java 8 is.

**Comment by adamreed90** [comment]
Any core developers alive?

**Comment by GNUDimarik** [comment]
Hi.
Any logs?

**Comment by kai-girke-sm** [comment]
We encounter same problem after reboot jitsi won't start anymore.
How we can record logs if the application not start....
After a re-installation it worked again.  
This is the only thing that mentioned as severe in the logs.

2019-11-19 16:27:18.865 SEVERE: [20] org.jitsi.impl.neomedia.device.DeviceConfiguration.log() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer with JMF.
java.lang.UnsatisfiedLinkError: C:\Users\....\AppData\Local\Temp\jna-795080503\jna3026429691419421564.dll: The specified procedure could not be found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.jitsi.util.JNIUtils.loadLibrary(JNIUtils.java:104)
	at org.jitsi.util.JNIUtils.loadLibrary(JNIUtils.java:40)
	at org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer.<clinit>(JAWTRenderer.java:99)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1046)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:365)
	at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:160)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
	at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
	at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:95)
	at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:172)
	at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:124)
	at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:391)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2226)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
