### ISSUE TITLE
NoClassDefFoundError: org/jitsi/utils/StringUtils at PopupMessageNotificationHandlerImpl

### ISSUE THREAD

**Issue by basinilya** [jitsi/jitsi#600]
## Description
When launching the current master (`8cf8623`) and when receiving a text message on a SIP account this error is printed to log: `NoClassDefFoundError: org/jitsi/utils/StringUtils ... at PopupMessageNotificationHandlerImpl` (see below full log)

Quick check shown that the code is running inside the Felix classloader and I'm not familiar with it to debug further.

## Current behavior
Error is printed, however, the program doesn't crash.

## Expected Behavior
Not sure how the notification should look like

## Possible Solution
---

## Steps to reproduce

    git clone ...
    ant rebuild
    ant run

- go online with a SIP account and try to receive a text message from another user

# Environment details
Windows 7 64-bit

     2019-06-29 13:27:53.256 SEVERE: [79] plugin.notificationwiring.NotificationManager.messageReceived().1304 Error notifying for message received
     java.lang.NoClassDefFoundError: org/jitsi/utils/StringUtils
         at net.java.sip.communicator.impl.notification.PopupMessageNotificationHandlerImpl.popupMessage(PopupMessageNotificationHandlerImpl.java:70)
         at net.java.sip.communicator.service.notification.NotificationServiceImpl.fireNotification(NotificationServiceImpl.java:251)
         at net.java.sip.communicator.service.notification.NotificationServiceImpl.fireNotification(NotificationServiceImpl.java:385)
         at net.java.sip.communicator.plugin.notificationwiring.NotificationManager.fireChatNotification(NotificationManager.java:214)
         at net.java.sip.communicator.plugin.notificationwiring.NotificationManager.messageReceived(NotificationManager.java:1295)
         at net.java.sip.communicator.service.protocol.AbstractOperationSetBasicInstantMessaging.fireMessageEvent(AbstractOperationSetBasicInstantMessaging.java:232)
         at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicInstantMessagingSipImpl.access$800(OperationSetBasicInstantMessagingSipImpl.java:40)
         at net.java.sip.communicator.impl.protocol.sip.OperationSetBasicInstantMessagingSipImpl$BasicInstantMessagingMethodProcessor.processRequest(OperationSetBasicInstantMessaga:807)
         at net.java.sip.communicator.impl.protocol.sip.ProtocolProviderServiceSipImpl.processRequest(ProtocolProviderServiceSipImpl.java:1114)
         at net.java.sip.communicator.impl.protocol.sip.SipStackSharing.processRequest(SipStackSharing.java:732)
         at gov.nist.javax.sip.EventScanner.deliverRequestEvent(EventScanner.java:250)
         at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:146)
         at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185)
         at gov.nist.javax.sip.DialogFilter.processRequest(DialogFilter.java:1324)
         at gov.nist.javax.sip.stack.SIPServerTransactionImpl.processRequest(SIPServerTransactionImpl.java:811)
         at gov.nist.javax.sip.stack.ConnectionOrientedMessageChannel.processMessage(ConnectionOrientedMessageChannel.java:466)
         at gov.nist.javax.sip.parser.PipelinedMsgParser.run(PipelinedMsgParser.java:541)
         at java.lang.Thread.run(Thread.java:748)
     Caused by: java.lang.ClassNotFoundException: org.jitsi.utils.StringUtils not found by net.java.sip.communicator.notification [22]
         at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1639)
         at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
         at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
         ... 18 more

**Comment by GNUDimarik** [comment]
This is know issue. Here is discussion: https://github.com/jitsi/jitsi/issues/435
Once I have time on it it should be fixed. Please see dicussion for more details

**Comment by GNUDimarik** [comment]
@ibauersachs please let me know. Is this acceptable build.xml will download depenencies?

**Comment by GNUDimarik** [comment]
@ibauersachs sorry. I don't remember where we discussed it previously. Let's move discussion here since this is related issue

**Comment by damencho** [comment]
Dependencies are not downloaded and this is a manifest problem, missing some imports since we moved many things around ... I said I will work on that at some point, but haven't found a free time to do so.

**Comment by GNUDimarik** [comment]
@damencho then you able to guide me about thing you wanted to do :-)
Please explain me your approach I'll work on this

**Comment by damencho** [comment]
Well, this is a simple OSGi problem. The approach is running and seeing the problems in the logs or check all the modifications around utils packages, in which bundles it was added and which of those miss the package in the manifest.

The error above is from the bundle which handles 'net.java.sip.communicator.notification' which is https://github.com/jitsi/jitsi/blob/733191f0cae2b142d6949309415e643ecd5fcabe/src/net/java/sip/communicator/impl/notification/notification.manifest.mf#L6 and that manifest is missing that org.jitsi.utils package.

**Comment by GNUDimarik** [comment]
I understand. But since we decided to leave jitsi.utins please advice me the approach to add new dependency to the project

**Comment by damencho** [comment]
I'm confused, what is your question?

**Comment by damencho** [comment]
I just pushed, and the NoClassDefFoundError should be fixed.

**Comment by damencho** [comment]
Fixed with 2d80de7.

**Comment by GNUDimarik** [comment]
@damencho I meant we decided to move to Apache StringUtils. And I need some place where I able to add corresponding dependency

**Comment by damencho** [comment]
So this is dependency on commons-lang3-3.1.jar already exists.
https://github.com/jitsi/jitsi/blob/master/lib/installer-exclude/commons-lang3-3.1.jar
https://github.com/jitsi/jitsi/blob/master/lib/installer-exclude/commons-lang3-3.1.manifest.mf

**Comment by GNUDimarik** [comment]
@damencho great thanks!
WIll work on this then!
