### ISSUE TITLE
Sign-in says Failed to initialize accountFailed to get SIP Factory

### ISSUE THREAD

**Issue by divansantana** [jitsi/jitsi#649]
Trying to get this to work on [guix](https://www.gnu.org/software/guix)

launched via `java -jar jitsi-2.11.5629.jar` which installs to ~/jitsi

My java is `/gnu/store/xcf8b88l07i38hwjpjfxk9wfralpy01j-icedtea-3.7.0/bin/java`

from guix

```
$ java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (IcedTea 3.7.0) (guix build 1.8.0_161-b12)
OpenJDK 64-Bit Server VM (build 25.161-b12, mixed mode)
```

On launch I get this. Yet the screen opens and all appears to work
fine.

```
  ds@swift ~/jitsi $ ./run.sh
  Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd
  java.lang.NoClassDefFoundError: org/xbill/DNS/Resolver
          at java.lang.Class.getDeclaredConstructors0(Native Method)
          at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
          at java.lang.Class.getConstructor0(Class.java:3075)
          at java.lang.Class.newInstance(Class.java:412)
          at org.apache.felix.framework.Felix.createBundleActivator(Felix.java:4512)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2221)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.ClassNotFoundException: org.xbill.DNS.Resolver
          at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
          at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
          at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:940)
          at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
          at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
          at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
          at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
          ... 10 more
  java.lang.NoClassDefFoundError: org/xbill/DNS/TextParseException
          at net.java.sip.communicator.impl.netaddr.NetworkAddressManagerServiceImpl.initRandomPortSocket(NetworkAddressManagerServiceImpl.java:433)
          at net.java.sip.communicator.impl.netaddr.NetworkAddressManagerServiceImpl.start(NetworkAddressManagerServiceImpl.java:107)
          at net.java.sip.communicator.impl.netaddr.NetaddrActivator.start(NetaddrActivator.java:89)
          at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.ClassNotFoundException: org.xbill.DNS.TextParseException
          at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
          at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
          at org.apache.felix.framework.ExtensionManager$ExtensionManagerWiring.getClassByDelegation(ExtensionManager.java:940)
          at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1660)
          at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1590)
          at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:80)
          at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2053)
          at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
          ... 9 more
  2020-03-12 15:30:23.619 SEVERE: [19] impl.sysactivity.SystemActivityNotificationsServiceImpl.getCurrentRunningManager().647 Error creating manager
  java.lang.UnsatisfiedLinkError: no unix-java in java.library.path
          at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
          at java.lang.Runtime.loadLibrary0(Runtime.java:870)
          at java.lang.System.loadLibrary(System.java:1122)
          at cx.ath.matthew.unix.UnixSocket.<clinit>(UnixSocket.java:40)
          at org.freedesktop.dbus.Transport.connect(Unknown Source)
          at org.freedesktop.dbus.Transport.<init>(Unknown Source)
          at org.freedesktop.dbus.DBusConnection.<init>(Unknown Source)
          at org.freedesktop.dbus.DBusConnection.getConnection(Unknown Source)
          at net.java.sip.communicator.impl.sysactivity.NetworkManagerListenerImpl.<init>(NetworkManagerListenerImpl.java:56)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at java.lang.Class.newInstance(Class.java:442)
          at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.getCurrentRunningManager(SystemActivityNotificationsServiceImpl.java:643)
          at net.java.sip.communicator.impl.sysactivity.SystemActivityNotificationsServiceImpl.start(SystemActivityNotificationsServiceImpl.java:154)
          at net.java.sip.communicator.impl.sysactivity.SysActivityActivator.start(SysActivityActivator.java:70)
          at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)
  2020-03-12 15:30:23.919 SEVERE: [19] impl.hid.HIDServiceImpl.<init>().66 Error when creating Robot/NativeKeyboard instance
  java.lang.UnsatisfiedLinkError: no hid in java.library.path
          at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
          at java.lang.Runtime.loadLibrary0(Runtime.java:870)
          at java.lang.System.loadLibrary(System.java:1122)
          at net.java.sip.communicator.impl.hid.NativeKeyboard.<clinit>(NativeKeyboard.java:29)
          at net.java.sip.communicator.impl.hid.HIDServiceImpl.<init>(HIDServiceImpl.java:61)
          at net.java.sip.communicator.impl.hid.HIDActivator.start(HIDActivator.java:59)
          at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)
  2020-03-12 15:30:24.407 SEVERE: [19] org.jitsi.impl.neomedia.device.DeviceConfiguration.log() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer with JMF.
  java.lang.IllegalStateException: audioSystem
          at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:156)
          at org.jitsi.impl.neomedia.jmfext.media.renderer.audio.PulseAudioRenderer.<init>(PulseAudioRenderer.java:136)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at java.lang.Class.newInstance(Class.java:442)
          at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1047)
          at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:366)
          at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:162)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at java.lang.Class.newInstance(Class.java:442)
          at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
          at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
          at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
          at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:95)
          at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:172)
          at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:124)
          at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:391)
          at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)
  2020-03-12 15:30:24.417 SEVERE: [19] org.jitsi.impl.neomedia.device.DeviceConfiguration.log() Failed to register custom Renderer org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer with JMF.
  java.lang.UnsatisfiedLinkError: Directory separator should not appear in library name: /tmp/jna-3215/jna4142418299121197835.tmp
          at java.lang.Runtime.loadLibrary0(Runtime.java:867)
          at java.lang.System.loadLibrary(System.java:1122)
          at org.jitsi.utils.JNIUtils.loadNativeInClassloader(JNIUtils.java:137)
          at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:86)
          at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:45)
          at org.jitsi.impl.neomedia.jmfext.media.renderer.video.JAWTRenderer.<clinit>(JAWTRenderer.java:101)
          at java.lang.Class.forName0(Native Method)
          at java.lang.Class.forName(Class.java:264)
          at org.jitsi.impl.neomedia.device.DeviceConfiguration.registerCustomRenderers(DeviceConfiguration.java:1047)
          at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:366)
          at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:162)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at java.lang.Class.newInstance(Class.java:442)
          at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
          at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
          at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
          at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:95)
          at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:172)
          at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:124)
          at net.java.sip.communicator.impl.neomedia.NeomediaActivator.start(NeomediaActivator.java:391)
          at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)
  java.lang.NullPointerException
          at net.java.sip.communicator.plugin.reconnectplugin.ReconnectPluginActivator.start(ReconnectPluginActivator.java:172)
          at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)

  (java:13190): Gtk-WARNING **: 15:30:24.856: Unable to locate theme engine in module_path: "adwaita",

  (java:13190): Gtk-WARNING **: 15:30:24.863: Unable to locate theme engine in module_path: "adwaita",
  java.lang.UnsatisfiedLinkError: no globalshortcut in java.library.path
          at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
          at java.lang.Runtime.loadLibrary0(Runtime.java:870)
          at java.lang.System.loadLibrary(System.java:1122)
          at net.java.sip.communicator.impl.globalshortcut.NativeKeyboardHook.<clinit>(NativeKeyboardHook.java:265)
          at net.java.sip.communicator.impl.globalshortcut.GlobalShortcutServiceImpl.<init>(GlobalShortcutServiceImpl.java:67)
          at net.java.sip.communicator.impl.globalshortcut.GlobalShortcutActivator.start(GlobalShortcutActivator.java:112)
          at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)
  java.lang.NullPointerException
          at net.java.sip.communicator.plugin.pluginmanager.PluginManagerActivator.start(PluginManagerActivator.java:99)
          at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)
  java.lang.UnsatisfiedLinkError: no jdic_misc in java.library.path
          at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
          at java.lang.Runtime.loadLibrary0(Runtime.java:870)
          at java.lang.System.loadLibrary(System.java:1122)
          at org.jdesktop.jdic.misc.impl.LinuxAlerter.<init>(LinuxAlerter.java:48)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
          at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
          at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
          at java.lang.Class.newInstance(Class.java:442)
          at org.jdesktop.jdic.misc.Alerter.loadLinux(Unknown Source)
          at org.jdesktop.jdic.misc.Alerter.newInstance(Unknown Source)
          at net.java.sip.communicator.plugin.chatalerter.ChatAlerterActivator.start(ChatAlerterActivator.java:99)
          at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
          at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
          at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
          at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
          at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
          at java.lang.Thread.run(Thread.java:748)
```

I then configure a SIP account and when clicking "sign in" I get this:

```
  java.lang.RuntimeException: Failed to initialize accountFailed to get SIP Factory
          at net.java.sip.communicator.impl.gui.main.account.AccountRegSummaryPage.commitPage(AccountRegSummaryPage.java:236)
          at net.java.sip.communicator.impl.gui.customcontrols.wizard.WizardController$PageCommitThread.run(WizardController.java:156)
          at java.lang.Thread.run(Thread.java:748)
  Caused by: net.java.sip.communicator.service.protocol.OperationFailedException: Failed to initialize accountFailed to get SIP Factory
          at net.java.sip.communicator.plugin.sipaccregwizz.SIPAccountRegistrationWizard.installAccount(SIPAccountRegistrationWizard.java:442)
          at net.java.sip.communicator.plugin.sipaccregwizz.SIPAccountRegistrationWizard.signin(SIPAccountRegistrationWizard.java:369)
          at net.java.sip.communicator.plugin.sipaccregwizz.SIPAccountRegistrationWizard.signin(SIPAccountRegistrationWizard.java:344)
          at net.java.sip.communicator.impl.gui.main.account.AccountRegSummaryPage.commitPage(AccountRegSummaryPage.java:192)
          ... 2 more
```

Anyone have a clue what I can try to get this to work?

**Comment by damencho** [comment]
Where did you get the jat file from?
This is the sh file that is uptodate and you can use to start jitsi https://github.com/jitsi/jitsi/blob/master/resources/install/debian/jitsi.sh.tmpl but it needs the specific structure of files used for the Debian packages ... it should be very close to what is in the sourcecode ... 
Or you can just do `ant rebuild run`.

**Comment by divansantana** [comment]
Thanks for the quick reply.

I got it here https://download.jitsi.org/jitsi/nightly/generic/

I'm not familiar with ant.

So what would a general approach be to getting this to run on guix (besides doing a proper package for it).

```
git clone this project
cd src/somedir
ant rebuild run
```

**Comment by damencho** [comment]
Yes.

**Comment by divansantana** [comment]
Cool, sorted.
