### ISSUE TITLE
jitsi fails on FreeBSD: missing requirement osgi.native

### ISSUE THREAD

**Issue by yurivict** [jitsi/jitsi#652]
jitsi-2.10.5550 prints a lot of these:
```
org.osgi.framework.BundleException: Unable to resolve org.jitsi.libjitsi [107](R 107.0): missing requirement [org.jitsi.libjitsi [107](R 107.0)] osgi.native; (|(&(osgi.native.osname~=mac os x)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64))) Unresolved requirements: [[org.jitsi.libjitsi [107](R 107.0)] osgi.native; (|(&(osgi.native.osname~=mac os x)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64)))]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
org.osgi.framework.BundleException: Unable to resolve net.java.sip.communicator.service.util [26](R 26.0): missing requirement [net.java.sip.communicator.service.util [26](R 26.0)] osgi.wiring.package; (osgi.wiring.package=net.java.sip.communicator.service.resources) [caused by: Unable to resolve net.java.sip.communicator.resources [87](R 87.0): missing requirement [net.java.sip.communicator.resources [87](R 87.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.service.configuration) [caused by: Unable to resolve org.jitsi.libjitsi [107](R 107.0): missing requirement [org.jitsi.libjitsi [107](R 107.0)] osgi.native; (|(&(osgi.native.osname~=mac os x)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64)))]] Unresolved requirements: [[net.java.sip.communicator.service.util [26](R 26.0)] osgi.wiring.package; (osgi.wiring.package=net.java.sip.communicator.service.resources)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
org.osgi.framework.BundleException: Unable to resolve net.java.sip.communicator.fileaccess [29](R 29.0): missing requirement [net.java.sip.communicator.fileaccess [29](R 29.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.service.libjitsi) [caused by: Unable to resolve org.jitsi.libjitsi [107](R 107.0): missing requirement [org.jitsi.libjitsi [107](R 107.0)] osgi.native; (|(&(osgi.native.osname~=mac os x)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64)))] Unresolved requirements: [[net.java.sip.communicator.fileaccess [29](R 29.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.service.libjitsi)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
org.osgi.framework.BundleException: Unable to resolve net.java.sip.communicator.plugin.defaultresourcepack [30](R 30.0): missing requirement [net.java.sip.communicator.plugin.defaultresourcepack [30](R 30.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.service.resources) [caused by: Unable to resolve org.jitsi.libjitsi [107](R 107.0): missing requirement [org.jitsi.libjitsi [107](R 107.0)] osgi.native; (|(&(osgi.native.osname~=mac os x)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86))(&(osgi.native.osname~=linux)(osgi.native.processor~=x86-64))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86))(&(osgi.native.osname~=win32)(osgi.native.processor~=x86-64)))] Unresolved requirements: [[net.java.sip.communicator.plugin.defaultresourcepack [30](R 30.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.service.resources)]
        at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4111)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2117)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by joerghohn** [comment]
same on "MX Linux 19.1" (Debian 10.3 based).

**Comment by bnounours** [comment]
Same for me on Ubuntu 20.10

**Comment by rpecosta95** [comment]
Same for me on Mint 20.3 (Una)
