### ISSUE TITLE
Camera not working anymore after last Update.

### ISSUE THREAD

**Issue by JPRuehmann** [jitsi/jitsi#716]
I've Updated Jitsi to 2.11.5624
Since then my Camera a Logitech 920 is not working anymore and the H264 Codec is gone.
How can i make it work again?

In the V4L Test tools it is working, in the old vesion it was working.
I am using Kubuntu 18.04 LTE (32Bit)
Java 1.8.0_144

**Comment by jose1711** [comment]
I think it would be useful to paste an error you get in the console. My camera isn't working either - no preview (Arch Linux, both nightly and the latest stable) but not sure if this is the same issue as yours. The error I get is this:
```
2021-01-17 00:04:05.068 SEVERE: [132] util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[FMJ Thread: net.sf.fmj.media.ProcessEngine@78743a6[ net.sf.fmj.media.ProcessEngine@78743a6 ] ( realizeThread),9,system] and message was: Could not initialize class org.jitsi.impl.neomedia.codec.FFmpeg
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.impl.neomedia.codec.FFmpeg
	at org.jitsi.impl.neomedia.codec.video.HFlip.doOpen(HFlip.java:150)
	at org.jitsi.impl.neomedia.codec.AbstractCodec2.open(AbstractCodec2.java:412)
	at net.sf.fmj.media.BasicFilterModule.doRealize(BasicFilterModule.java:83)
	at net.sf.fmj.media.PlaybackEngine.buildTrackFromGraph(PlaybackEngine.java:579)
	at net.sf.fmj.media.ProcessEngine$ProcGraphBuilder.buildTrackFromGraph(ProcessEngine.java:262)
	at net.sf.fmj.media.ProcessEngine$ProcGraphBuilder.buildCustomGraph(ProcessEngine.java:239)
	at net.sf.fmj.media.ProcessEngine$ProcGraphBuilder.buildGraph(ProcessEngine.java:252)
	at net.sf.fmj.media.ProcessEngine$ProcTControl.buildTrack(ProcessEngine.java:688)
	at net.sf.fmj.media.PlaybackEngine.doRealize1(PlaybackEngine.java:1135)
	at net.sf.fmj.media.ProcessEngine.doRealize(ProcessEngine.java:1197)
	at net.sf.fmj.media.RealizeWorkThread.process(BasicController.java:1145)
	at net.sf.fmj.media.StateTransitionWorkThread.run(BasicController.java:1224)
```

**Comment by JPRuehmann** [comment]
I get this in the Terminal
```
2021-01-17 09:14:18.146 SCHWERWIEGEND: [61] util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[FMJ Thread: net.sf.fmj.media.ProcessEngine@17da52[ net.sf.fmj.media.ProcessEngine@17da52 ] ( realizeThread),9,system] and message was: Could not initialize class org.jitsi.impl.neomedia.codec.FFmpeg
java.lang.NoClassDefFoundError: Could not initialize class org.jitsi.impl.neomedia.codec.FFmpeg
        at org.jitsi.impl.neomedia.codec.video.HFlip.doOpen(HFlip.java:150)
        at org.jitsi.impl.neomedia.codec.AbstractCodec2.open(AbstractCodec2.java:412)
        at net.sf.fmj.media.BasicFilterModule.doRealize(BasicFilterModule.java:83)
        at net.sf.fmj.media.PlaybackEngine.buildTrackFromGraph(PlaybackEngine.java:579)
        at net.sf.fmj.media.ProcessEngine$ProcGraphBuilder.buildTrackFromGraph(ProcessEngine.java:262)
        at net.sf.fmj.media.ProcessEngine$ProcGraphBuilder.buildCustomGraph(ProcessEngine.java:239)
        at net.sf.fmj.media.ProcessEngine$ProcGraphBuilder.buildGraph(ProcessEngine.java:252)
        at net.sf.fmj.media.ProcessEngine$ProcTControl.buildTrack(ProcessEngine.java:688)
        at net.sf.fmj.media.PlaybackEngine.doRealize1(PlaybackEngine.java:1135)
        at net.sf.fmj.media.ProcessEngine.doRealize(ProcessEngine.java:1197)
        at net.sf.fmj.media.RealizeWorkThread.process(BasicController.java:1145)
        at net.sf.fmj.media.StateTransitionWorkThread.run(BasicController.java:1224)
```
Thanks,
