### ISSUE TITLE
Update of libjitsi.jar is required - otherwise jitsi not starting with Unable to resolve errors

### ISSUE THREAD

**Issue by jose1711** [jitsi/jitsi#748]
## Description
Currently the `PKGUILD` to build `jitsi` in Arch uses an ugly hack manually updating manifest in `lijitsi.jar`: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jitsi-nightly#n67

```
jar uvfm "${pkgdir}/usr/lib/jitsi/sc-bundles/libjitsi.jar" MANIFEST.MF
```

## Current behavior
If this step is skipped (no update) `jitsi` prints many errors on stdout and refuses to start:
```
org.osgi.framework.BundleException: Unable to resolve net.java.sip.communicator.argdelegation [154](R 154.0): missing requirement [net.java.sip.communicator.argdelegation [154](R 154.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.util) [caused by: Unable to resolve org.jitsi.libjitsi [126](R 126.0): missing requirement [org.jitsi.libjitsi [126](R 126.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.jna)(version>=5.5.0)(!(version>=6.0.0)))] Unresolved requirements: [[net.java.sip.communicator.argdelegation [154](R 154.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.util)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
org.osgi.framework.BundleException: Unable to resolve net.java.sip.communicator.shutdowntimeout [75](R 75.0): missing requirement [net.java.sip.communicator.shutdowntimeout [75](R 75.0)] osgi.wiring.package; (osgi.wiring.package=net.java.sip.communicator.util) [caused by: Unable to resolve net.java.sip.communicator.service.util [96](R 96.0): missing requirement [net.java.sip.communicator.service.util [96](R 96.0)] osgi.wiring.package; (osgi.wiring.package=net.java.sip.communicator.service.gui.call) [caused by: Unable to resolve net.java.sip.communicator.service.gui [58](R 58.0): missing requirement [net.java.sip.communicator.service.gui [58](R 58.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.service.resources) [caused by: Unable to resolve org.jitsi.libjitsi [126](R 126.0): missing requirement [org.jitsi.libjitsi [126](R 126.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.jna)(version>=5.5.0)(!(version>=6.0.0)))]]] Unresolved requirements: [[net.java.sip.communicator.shutdowntimeout [75](R 75.0)] osgi.wiring.package; (osgi.wiring.package=net.java.sip.communicator.util)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4149)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2119)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1373)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)
```

## Expected Behavior
There should be a better solution.

## Possible Solution
Not known.

# Environment details
I am aware of the fact that `ant` is used instead of `mvn` to build the package but I have adopted this approach and it seems to work fine otherwise.

**Comment by damencho** [comment]
And what is the difference with the original one?

**Comment by jose1711** [comment]
The diff produced is almost unreadable hence attaching both manifests in full.

The original one is [MANIFEST.MF.broken.txt](https://github.com/jitsi/jitsi/files/7231177/MANIFEST.MF.broken.txt).

The one that works is [MANIFEST.MF.working.txt](https://github.com/jitsi/jitsi/files/7231178/MANIFEST.MF.working.txt).

**Comment by damencho** [comment]
Then how did you produce the working one? Where did you get it from?

**Comment by jose1711** [comment]
This was a very good question. I did find `jitsi-nightly` compiled and installed back in April 2021 on my laptop. After making a backup of the installed files I started comparing the current and previous files (really trial&error approach). That's how I found the thing with manifest.
Note that if I went and compiled the same version it did not start either. And it just hit me.. so far I was always looking at Jitsi's requirements like `java` and/or version of `ffmpeg`. What I did now was try to use older snapshot of Jitsi source code and looks like the problem came with the [latest commit](https://github.com/jitsi/jitsi/commit/c81e58f1a9c63b60f6ebbccfca113906472b186b) in master. As soon as I checkout HEAD~1 no manifest update is required.
