### ISSUE TITLE
dpkg on debian buster fails due to zstd compressed files in lua-basexx and lua-cjson

### ISSUE THREAD

**Issue by WhoAmI0501** [jitsi/jitsi#767]
Hi,
i recently updated my jitsi meet installation and apt has thrown the following error:
```bash
root@jitsi:~# apt upgrade
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Die folgenden Pakete werden aktualisiert (Upgrade):
  lua-basexx lua-cjson
2 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen 26,8 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 105 kB Plattenplatz zusätzlich benutzt.
Möchten Sie fortfahren? [J/n] y
Holen:1 https://download.jitsi.org stable/ lua-basexx 0.4.1-jitsi1 [4.284 B]  
Holen:2 https://download.jitsi.org stable/ lua-cjson 2.1.0.10-jitsi1 [22,5 kB]
Es wurden 26,8 kB in 1 s geholt (24,7 kB/s).
dpkg-deb: Fehler: Archiv »/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb« verwendet unbekannte Komprimierung für Element »control.tar.zst«, Abbruch
Traceback (most recent call last):
  File "/usr/share/apt-listchanges/DebianFiles.py", line 124, in readdeb
    output = subprocess.check_output(command)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dpkg-deb', '-f', '/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb', 'Package', 'Source', 'Version', 'Architecture', 'Status']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/apt-listchanges", line 281, in <module>
    main(config)
  File "/usr/bin/apt-listchanges", line 96, in main
    pkg = DebianFiles.Package(deb)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 215, in __init__
    parser.readdeb(self.path)
  File "/usr/share/apt-listchanges/DebianFiles.py", line 128, in readdeb
    {'what': file, 'errmsg': str(ex)}) from ex
NameError: name 'file' is not defined
dpkg-deb: Fehler: Archiv »/var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb« verwendet unbekannte Komprimierung für Element »control.tar.zst«, Abbruch
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb (--unpack):
 »dpkg-deb --control«-Unterprozess gab den Fehlerwert 2 zurück
dpkg-deb: Fehler: Archiv »/var/cache/apt/archives/lua-cjson_2.1.0.10-jitsi1_amd64.deb« verwendet unbekannte Komprimierung für Element »control.tar.zst«, Abbruch
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/lua-cjson_2.1.0.10-jitsi1_amd64.deb (--unpack):
 »dpkg-deb --control«-Unterprozess gab den Fehlerwert 2 zurück
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/lua-basexx_0.4.1-jitsi1_all.deb
 /var/cache/apt/archives/lua-cjson_2.1.0.10-jitsi1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@jitsi:~#
```

First - zstd is installed on my system:
```bash
root@jitsi:~# apt install -y zstd
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
zstd ist schon die neueste Version (1.3.8+dfsg-3+deb10u2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 2 nicht aktualisiert.
root@jitsi:~# 
```

As i have had read in the internet, zstd compression is only supported in dpkg on Ubuntu... my jitsimeet installation isnt broken, but its quiet unsatisfying when i am not able to install open updates.

**Comment by WhoAmI0501** [comment]
Shit, wrong GitHub project... i will move this.

**Comment by meepmeep** [comment]
Hi
Why is it the wrong project ? both package are downloaded from jitsi.org website, and use an incorrect compression
```
Holen:1 https://download.jitsi.org stable/ lua-basexx 0.4.1-jitsi1 [4.284 B]  
Holen:2 https://download.jitsi.org stable/ lua-cjson 2.1.0.10-jitsi1 [22,5 kB]
```

**Comment by WhoAmI0501** [comment]
Because these packages are related to the Jitsi Meet server and this repository belongs to the Jitsi client.

Am 21. September 2022 11:22:43 UTC schrieb meepmeep ***@***.***>:
