### ISSUE TITLE
No sound under Fedora (GNOME Desktop)?

### ISSUE THREAD

**Issue by Af0x** [jitsi/jitsi#769]
Hello,

can anyone confirm that with Fedora 36 there is no sound at all (mic and speaker) inside jitsi?

When I go to `Tools > Options > Audio > Audio System` there is only one device called `audiosilence`.

I have to add that this can also be a building issue as I did some nasty stuff to get jitsi installed on my Fedora OS (converted the .deb  file with alien).

I cloned the jitsi repo today.

Best regards

**Comment by damencho** [comment]
Yep, it is not loading pulseaudio module for some reason. Is this master you are trying?

**Comment by foxbow** [comment]
Yep, checked out today and did the 'mvn package -DskipTest', cd native 'cmake -Bcmake-make', 'cmake --build cmake-build --target install' combo and then started it with the snippet from the 'hacking.md' all with openjdk 11.0.16

**Comment by foxbow** [comment]
Brute-force-feeding the library in by unpacking the libjitsi jar and copying the libraries into the expected path made that one go away, but the next one immediately followed up:

`14:26:53.016 [FelixStartLevel] INFO org.jitsi.impl.neomedia.device.DeviceSystem - Initializing audio devices
14:26:53.026 [FelixStartLevel] WARN org.jitsi.impl.neomedia.device.DeviceSystem - Failed to initialize org.jitsi.impl.neomedia.device.PulseAudioSystem
java.lang.NoClassDefFoundError: org/jitsi/impl/neomedia/pulseaudio/PA$sink_info_cb_t
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2445)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2501)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2700)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:58)
	at org.jitsi.utils.JNIUtils.loadLibrary(JNIUtils.java:43)
	at org.jitsi.impl.neomedia.pulseaudio.PA.<clinit>(PA.java:125)
	at org.jitsi.impl.neomedia.device.PulseAudioSystem.startMainloop(PulseAudioSystem.java:677)
	at org.jitsi.impl.neomedia.device.PulseAudioSystem.createContext(PulseAudioSystem.java:140)
	at org.jitsi.impl.neomedia.device.PulseAudioSystem.getContext(PulseAudioSystem.java:493)
	at org.jitsi.impl.neomedia.device.PulseAudioSystem.doInitialize(PulseAudioSystem.java:357)
	at org.jitsi.impl.neomedia.device.DeviceSystem.initialize(DeviceSystem.java:641)
	at org.jitsi.impl.neomedia.device.DeviceSystem.invokeDeviceSystemInitialize(DeviceSystem.java:446)
	at org.jitsi.impl.neomedia.device.DeviceSystem.invokeDeviceSystemInitialize(DeviceSystem.java:349)
	at org.jitsi.impl.neomedia.device.DeviceSystem.<init>(DeviceSystem.java:494)
	at org.jitsi.impl.neomedia.device.AudioSystem.<init>(AudioSystem.java:204)
	at org.jitsi.impl.neomedia.device.PulseAudioSystem.<init>(PulseAudioSystem.java:128)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.jitsi.impl.neomedia.device.DeviceSystem.initializeDeviceSystems(DeviceSystem.java:289)
	at org.jitsi.impl.neomedia.device.DeviceSystem.initializeDeviceSystems(DeviceSystem.java:231)
	at org.jitsi.impl.neomedia.device.DeviceSystem.initializeDeviceSystems(DeviceSystem.java:161)
	at org.jitsi.impl.neomedia.device.DeviceConfiguration.<init>(DeviceConfiguration.java:348)
	at org.jitsi.impl.neomedia.MediaServiceImpl.<init>(MediaServiceImpl.java:163)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.initializeService(LibJitsiImpl.java:196)
	at org.jitsi.impl.libjitsi.LibJitsiImpl$ServiceLock.getService(LibJitsiImpl.java:131)
	at org.jitsi.impl.libjitsi.LibJitsiImpl.getService(LibJitsiImpl.java:91)
	at org.jitsi.impl.libjitsi.LibJitsiOSGiImpl.getService(LibJitsiOSGiImpl.java:69)
	at org.jitsi.service.libjitsi.LibJitsi.invokeGetServiceOnImpl(LibJitsi.java:170)
	at org.jitsi.service.libjitsi.LibJitsi.getMediaService(LibJitsi.java:122)
	at net.java.sip.communicator.impl.neomedia.NeomediaActivator.startWithServices(NeomediaActivator.java:417)
	at net.java.sip.communicator.util.osgi.DependentActivator.addingService(DependentActivator.java:103)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:944)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:872)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:904)
	at org.apache.felix.framework.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:990)
	at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:838)
	at org.apache.felix.framework.EventDispatcher.fireServiceEvent(EventDispatcher.java:545)
	at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4863)
	at org.apache.felix.framework.Felix.registerService(Felix.java:3834)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:328)
	at org.apache.felix.framework.BundleContextImpl.registerService(BundleContextImpl.java:335)
	at net.java.sip.communicator.impl.resources.ResourceManagementActivator.startWithServices(ResourceManagementActivator.java:54)
	at net.java.sip.communicator.util.osgi.DependentActivator.addingService(DependentActivator.java:103)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:944)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:872)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:322)
	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:265)
	at net.java.sip.communicator.util.osgi.DependentActivator.start(DependentActivator.java:79)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by foxbow** [comment]
@ibauersachs : removed  ~/.m2 and did a 'git clean -fdX' first.
'mvn package' still wants to test Win32LocalhostTest.testBestAdapterRoute on a Linux host
'mvn package -DskipTest' passes
change to native
'cmake -B cmake-build' and 'cmake --build cmake-build --target install' both pass

And success! I have pulseaudio and my microphone gets recognized!

**Comment by foxbow** [comment]
And I should probably have noted that I am on Ubuntu 20.04 ...

**Comment by ibauersachs** [comment]
I'm somewhat surprised this works at all :-D

The tests aren't working currently. Even if they'd find all the required dependencies in a mocked OSGi environment, they mostly need external servers to run (i.e. a SIP and XMPP server).

If you have ideas on how to improve the build, please comment in #764 or create a PR to the fix-installers branch.
